%% ========================================================================
% STEP C: ANNUAL RCAm ECONOMY WITH REGIONAL TEMPERATURE IMPACTS
% ========================================================================
%
% Builds on the accepted five-year DICE-2016R climate-policy pathway by
% interpolating it annually and applying regional temperature impacts to
% RCAm output, capital, consumption and welfare.
%
% Regional savings rates are selected at five-year decision dates and held
% constant across the five annual periods beginning at each decision date.
% ========================================================================

clearvars;
clc;
close all;

%% CONFIGURATION

[maindir,~,~] = fileparts(mfilename('fullpath'));

if isempty(maindir)
    maindir = pwd;
end

addpath(maindir);

customdir = '2026-07_RCAM';
plots_dir = fullfile(maindir,'plots');

if ~exist(plots_dir,'dir')
    mkdir(plots_dir);
end

Params.savedir = fullfile(maindir,'output',customdir);

if ~exist(Params.savedir,'dir')
    mkdir(Params.savedir);
end

diary(fullfile(Params.savedir,'Step_C_messages.txt'));

Params.global_timestep = 5;
Params.regional_timestep = 1;
Params.timestep = Params.regional_timestep;
Params.consumption_floor = 1e-8;

%% LOAD THE ACCEPTED FIVE-YEAR STEP A PATHWAY

step_a_file = fullfile(maindir,'DICE2016R_baseline_results.mat');

assert(isfile(step_a_file), ...
    'Could not find Step A results: %s',step_a_file);

dice = load(step_a_file);

required_dice_variables = { ...
    'year','T_base','abaterate_base','Params'};

for ii = 1:numel(required_dice_variables)
    assert(isfield(dice,required_dice_variables{ii}), ...
        'Step A file is missing "%s".',required_dice_variables{ii});
end

year_dice = double(dice.year(:));
T_base_dice = double(dice.T_base(:));
abaterate_dice = double(dice.abaterate_base(:));

assert(numel(T_base_dice) == numel(year_dice) && ...
    numel(abaterate_dice) == numel(year_dice), ...
    'The saved DICE pathways have inconsistent lengths.');

assert(all(isfinite([year_dice;T_base_dice;abaterate_dice])), ...
    'The saved DICE pathway contains NaN or Inf.');

assert(all(diff(year_dice) == Params.global_timestep), ...
    ['DICE2016R_baseline_results.mat must contain the accepted ' ...
    'five-year DICE pathway.']);

if isfield(dice.Params,'timestep')
    assert(dice.Params.timestep == Params.global_timestep, ...
        'The saved DICE Params.timestep is not five years.');
end

model_start_year = year_dice(1);
model_end_year = year_dice(end);
H_dice = numel(year_dice);

year_annual = (model_start_year:model_end_year)';
H_annual = numel(year_annual);
five_year_idx = 1:Params.global_timestep:H_annual;

assert(numel(five_year_idx) == H_dice, ...
    'The annual and five-year horizons do not align.');

T_base_annual = interp1( ...
    year_dice,T_base_dice,year_annual,'linear');

abaterate_annual = interp1( ...
    year_dice,abaterate_dice,year_annual,'linear');

dice_temperature_knot_error = max(abs( ...
    T_base_annual(five_year_idx)-T_base_dice));

dice_abatement_knot_error = max(abs( ...
    abaterate_annual(five_year_idx)-abaterate_dice));

assert(dice_temperature_knot_error < 1e-12 && ...
    dice_abatement_knot_error < 1e-12, ...
    'Annual interpolation does not reproduce the saved DICE knots.');

fprintf('\n=== FIXED DICE PATHWAY LOADED ===\n');
fprintf('Source:                    %s\n',step_a_file);
fprintf('DICE timestep:             %d years\n',Params.global_timestep);
fprintf('Regional timestep:         %d year\n',Params.regional_timestep);
fprintf('DICE years:                %d to %d\n', ...
    model_start_year,model_end_year);

%% LOAD STEP B RCAm DATA

baseline_file = fullfile(maindir,'RCAm_SSP2_baseline.csv');
parameter_file = fullfile(maindir,'RCAm_fixed_parameters.csv');

assert(isfile(baseline_file), ...
    'Could not find RCAm baseline: %s',baseline_file);
assert(isfile(parameter_file), ...
    'Could not find RCAm parameters: %s',parameter_file);

rcam_baseline = readtable(baseline_file);
rcam_params = readtable(parameter_file);

required_baseline_vars = [ ...
    "year","ykali","ykali_ppp","population", ...
    "carbon_intensity","savings_rate","investment", ...
    "capital","tfp","consumption","gdp_per_capita", ...
    "consumption_per_capita","baseline_co2_emissions"];

missing_baseline_vars = setdiff( ...
    required_baseline_vars, ...
    string(rcam_baseline.Properties.VariableNames));

assert(isempty(missing_baseline_vars), ...
    'RCAm baseline is missing: %s', ...
    strjoin(missing_baseline_vars,', '));

assert(all(ismember(["parameter","value"], ...
    string(rcam_params.Properties.VariableNames))), ...
    'RCAm parameter file must contain parameter and value columns.');

param_names = lower(strtrim(string(rcam_params.parameter)));

if isnumeric(rcam_params.value)
    param_values = double(rcam_params.value);
else
    param_values = str2double(erase(string(rcam_params.value),","));
end

assert(all(isfinite(param_values)), ...
    'RCAm parameter values must be numeric and finite.');

initial_capital_reg = get_parameter( ...
    param_names,param_values,"initial_capital_ppp");
initial_savings_reg = get_parameter( ...
    param_names,param_values,"initial_savings");
lrsavings_reg = get_parameter( ...
    param_names,param_values,"optimal_long_run_savings");
labour_share_reg = get_parameter( ...
    param_names,param_values,"labour_share");
capital_share_reg = get_parameter( ...
    param_names,param_values,"capital_share");
depreciation_reg = get_parameter( ...
    param_names,param_values,"depreciation_rate");
elasmu_reg = get_parameter( ...
    param_names,param_values,"elasticity_marginal_utility");
prstp_reg = get_parameter( ...
    param_names,param_values,"pure_rate_time_preference");
rcam_timestep = get_parameter( ...
    param_names,param_values,"timestep");
alpha_temp = get_parameter( ...
    param_names,param_values,"alpha_temp");
beta_temp = get_parameter( ...
    param_names,param_values,"beta_temp");
base_temp = get_parameter( ...
    param_names,param_values,"base_temp");
ppp2mer_reg = get_parameter( ...
    param_names,param_values,"ppp2mer");
mer2ppp_reg = get_parameter( ...
    param_names,param_values,"mer2ppp");

assert(abs(labour_share_reg+capital_share_reg-1) < 1e-8, ...
    'RCAm production shares must sum to one.');
assert(initial_capital_reg > 0, ...
    'Initial regional capital must be positive.');
assert(depreciation_reg >= 0 && depreciation_reg < 1, ...
    'The annual depreciation rate must lie in [0,1).');
assert(ppp2mer_reg > 0 && mer2ppp_reg > 0, ...
    'PPP/MER conversion factors must be positive.');
assert(abs(rcam_timestep-Params.global_timestep) < 1e-12, ...
    'Step B must contain the calibrated five-year RCAm data.');

%% INTERPOLATE EXTERNAL RCAm PATHWAYS ANNUALLY

rcam_year_raw = double(rcam_baseline.year);
ykali_mer_raw = double(rcam_baseline.ykali);
ykali_ppp_raw = double(rcam_baseline.ykali_ppp);
pop_raw = double(rcam_baseline.population);
carbon_intensity_raw = double(rcam_baseline.carbon_intensity);
savings_raw = double(rcam_baseline.savings_rate);
capital_raw = double(rcam_baseline.capital);
tfp_raw = double(rcam_baseline.tfp);
co2_baseline_raw = double(rcam_baseline.baseline_co2_emissions);

raw_data = [ ...
    rcam_year_raw,ykali_mer_raw,ykali_ppp_raw,pop_raw, ...
    carbon_intensity_raw,savings_raw,capital_raw, ...
    tfp_raw,co2_baseline_raw];

assert(all(isfinite(raw_data),'all'), ...
    'The RCAm baseline contains NaN, Inf, or nonnumeric values.');

[rcam_year_raw,sort_idx] = sort(rcam_year_raw);
ykali_mer_raw = ykali_mer_raw(sort_idx);
ykali_ppp_raw = ykali_ppp_raw(sort_idx);
pop_raw = pop_raw(sort_idx);
carbon_intensity_raw = carbon_intensity_raw(sort_idx);
savings_raw = savings_raw(sort_idx);
capital_raw = capital_raw(sort_idx);
tfp_raw = tfp_raw(sort_idx);
co2_baseline_raw = co2_baseline_raw(sort_idx);

assert(all(diff(rcam_year_raw) > 0), ...
    'RCAm years must be unique and increasing.');
assert(model_start_year >= rcam_year_raw(1) && ...
    model_end_year <= rcam_year_raw(end), ...
    'The DICE horizon is outside the RCAm data range.');

if any(savings_raw > 1)
    warning('Savings appear to be percentages; dividing by 100.');
    savings_raw = savings_raw./100;
end

assert(all(savings_raw >= 0 & savings_raw <= 1), ...
    'RCAm savings rates must lie in [0,1].');

Ybaseline_reg_mer_annual = interp1( ...
    rcam_year_raw,ykali_mer_raw,year_annual,'linear');
Ybaseline_reg_ppp_annual = interp1( ...
    rcam_year_raw,ykali_ppp_raw,year_annual,'linear');
pop_annual = interp1( ...
    rcam_year_raw,pop_raw,year_annual,'linear');
carbon_intensity_annual = interp1( ...
    rcam_year_raw,carbon_intensity_raw,year_annual,'linear');
co2_baseline_annual = interp1( ...
    rcam_year_raw,co2_baseline_raw,year_annual,'linear');
tfp_input_annual = interp1( ...
    rcam_year_raw,tfp_raw,year_annual,'linear');

savings_reference_five_year = interp1( ...
    rcam_year_raw,savings_raw,year_dice,'linear');
savings_reference_annual = interp1( ...
    year_dice,savings_reference_five_year,year_annual,'previous');

annual_external_data = [ ...
    Ybaseline_reg_mer_annual,Ybaseline_reg_ppp_annual,pop_annual, ...
    carbon_intensity_annual,co2_baseline_annual,tfp_input_annual, ...
    savings_reference_annual];

assert(all(isfinite(annual_external_data),'all'), ...
    'Annual interpolation produced NaN or Inf.');
assert(all(Ybaseline_reg_ppp_annual > 0) && all(pop_annual > 0), ...
    'Annual output and population must remain positive.');

savings_block_error = check_savings_blocks( ...
    savings_reference_annual,savings_reference_five_year, ...
    five_year_idx,H_dice);

assert(savings_block_error < 1e-12, ...
    'The reference savings rate changes inside a five-year block.');

fprintf('\n=== RCAm SAVINGS CHECK ===\n');
fprintf('Reference initial savings: %.15f\n', ...
    savings_reference_five_year(1));
fprintf('Parameter initial savings: %.15f\n',initial_savings_reg);
fprintf('Reference final savings:   %.15f\n', ...
    savings_reference_five_year(end));
fprintf('Long-run parameter:        %.15f\n',lrsavings_reg);

%% ANNUAL REGIONAL TEMPERATURE AND CHRONIC IMPACTS

T_region_annual = alpha_temp+beta_temp.*T_base_annual;
deltaT_region_annual = T_region_annual-base_temp;

kw_DT = 0.00641;
kw_DT_lag = 0.00345;
kw_TDT = -0.00105;
kw_TDT_lag = -0.000718;

BImpact_annual = zeros(H_annual,1);

for aa = 2:H_annual
    if year_annual(aa) <= 2020
        continue;
    end

    dT = T_region_annual(aa)-T_region_annual(aa-1);

    BImpact_annual(aa) = ...
        (kw_DT+kw_DT_lag).*dT + ...
        (kw_TDT+kw_TDT_lag).*dT.* ...
        (2.*dT+T_region_annual(aa-1));
end

omega_annual = zeros(H_annual,1);

for aa = 2:H_annual
    denominator = BImpact_annual(aa)+1./(1+omega_annual(aa-1));
    assert(denominator > 0, ...
        'Temperature-impact recursion failed in %d.',year_annual(aa));
    omega_annual(aa) = 1./denominator-1;
end

damfrac_annual = 1-1./(1+omega_annual);

assert(all(isfinite([T_region_annual;omega_annual;damfrac_annual])), ...
    'Annual temperature impacts contain NaN or Inf.');
assert(all(omega_annual > -1) && all(damfrac_annual < 1), ...
    'Annual temperature impacts are outside their valid range.');

%% CALIBRATE THE ANNUAL NO-DAMAGE ECONOMY

% The annual capital law changes the within-period timing. Annual TFP is
% therefore calibrated so that the no-damage annual economy reproduces the
% interpolated SSP2 output exactly, rather than drifting merely because the
% regional timestep changed.

K_reg_nodamage_annual = zeros(H_annual,1);
K_reg_nodamage_annual(1) = initial_capital_reg;

Inv_reg_nodamage_annual = ...
    savings_reference_annual.*Ybaseline_reg_ppp_annual;
C_reg_nodamage_annual = ...
    Ybaseline_reg_ppp_annual-Inv_reg_nodamage_annual;

for aa = 1:H_annual-1
    K_reg_nodamage_annual(aa+1) = ...
        (1-depreciation_reg).*K_reg_nodamage_annual(aa) + ...
        Inv_reg_nodamage_annual(aa);
end

tfp_annual = Ybaseline_reg_ppp_annual./( ...
    (pop_annual/1000).^labour_share_reg.* ...
    K_reg_nodamage_annual.^capital_share_reg);

Ygross_reg_nodamage_annual = tfp_annual.* ...
    (pop_annual/1000).^labour_share_reg.* ...
    K_reg_nodamage_annual.^capital_share_reg;

baseline_output_error = max(abs( ...
    Ygross_reg_nodamage_annual-Ybaseline_reg_ppp_annual));

CO2_reg_bau_reconstructed_annual = ...
    carbon_intensity_annual.*Ybaseline_reg_mer_annual;
baseline_emissions_error = max(abs( ...
    CO2_reg_bau_reconstructed_annual-co2_baseline_annual));

assert(baseline_output_error < 1e-10, ...
    'The annual no-damage economy does not reproduce SSP2 output.');

%% FIXED-SAVINGS ANNUAL REGIONAL ECONOMY

FixedData = make_simulation_data( ...
    H_annual,initial_capital_reg,depreciation_reg,tfp_annual, ...
    pop_annual,labour_share_reg,capital_share_reg,omega_annual, ...
    prstp_reg,elasmu_reg,Params.consumption_floor);

[ ...
    K_reg_annual,Ygross_reg_annual,Ynet_reg_annual, ...
    Inv_reg_annual,C_reg_annual,Welfare_reg ...
    ] = simulate_regional_economy( ...
    savings_reference_annual,FixedData);

EconomicLoss_reg_annual = ...
    Ygross_reg_annual-Ynet_reg_annual;
CapitalFeedbackLoss_reg_annual = ...
    Ybaseline_reg_ppp_annual-Ygross_reg_annual;
TotalOutputGap_reg_annual = ...
    Ybaseline_reg_ppp_annual-Ynet_reg_annual;

DirectDamagePctBaseline_reg_annual = ...
    100.*EconomicLoss_reg_annual./Ybaseline_reg_ppp_annual;
CapitalFeedbackLossPct_reg_annual = ...
    100.*CapitalFeedbackLoss_reg_annual./Ybaseline_reg_ppp_annual;
TotalOutputGapPct_reg_annual = ...
    100.*TotalOutputGap_reg_annual./Ybaseline_reg_ppp_annual;

decomposition_error_fixed = max(abs( ...
    TotalOutputGapPct_reg_annual - ...
    DirectDamagePctBaseline_reg_annual - ...
    CapitalFeedbackLossPct_reg_annual));

assert(decomposition_error_fixed < 1e-10, ...
    'The fixed-savings loss decomposition does not balance.');

C_per_capita_reg_annual = ...
    (C_reg_annual./pop_annual).*1000;
CO2_reg_annual = carbon_intensity_annual.* ...
    (1-abaterate_annual).*Ygross_reg_annual.*ppp2mer_reg;

%% OPTIMISE FIVE-YEAR SAVINGS DECISIONS USING ANNUAL UTILITY

assert(exist('fmincon','file') == 2, ...
    'Step C requires fmincon from the Optimization Toolbox.');

terminal_constant_periods = min(10,H_dice-2);

% Prevent the finite-horizon optimiser from creating an artificial final
% drop in savings. The terminal tail begins one node before the final ten
% DICE periods and is fixed at RCAm's calibrated long-run savings rate.
terminal_start = H_dice-terminal_constant_periods;
savings_initial_reg = savings_reference_five_year(1);

savings_progress = (0:H_dice-1)'./max(H_dice-1,1);
savings_lower_path = savings_initial_reg + ...
    (0.10-savings_initial_reg).*savings_progress;
savings_upper_path = savings_initial_reg + ...
    (0.45-savings_initial_reg).*savings_progress;

savings_decision_indices = (2:terminal_start-1)';
savings_guess_decision = ...
    savings_reference_five_year(savings_decision_indices);
savings_lower_decision = ...
    savings_lower_path(savings_decision_indices);
savings_upper_decision = ...
    savings_upper_path(savings_decision_indices);
savings_guess_decision = min(max( ...
    savings_guess_decision,savings_lower_decision), ...
    savings_upper_decision);

OptData = FixedData;
OptData.H_dice = H_dice;
OptData.terminal_start = terminal_start;
OptData.terminal_savings = lrsavings_reg;
OptData.savings_initial = savings_initial_reg;
OptData.node_index_annual = interp1( ...
    year_dice,(1:H_dice)',year_annual,'previous');

objective = @(x) regional_savings_objective(x,OptData);

optim_options = optimoptions(@fmincon, ...
    'Algorithm','interior-point', ...
    'StepTolerance',1e-10, ...
    'ConstraintTolerance',1e-10, ...
    'OptimalityTolerance',1e-9, ...
    'MaxFunctionEvaluations',1e5, ...
    'MaxIterations',5e3, ...
    'Display','final-detailed');

fprintf('\n=== ANNUAL RCAm SAVINGS OPTIMISATION ===\n');
fprintf('Five-year savings decisions: %d\n', ...
    numel(savings_guess_decision));
fprintf('Annual utility periods:      %d\n',H_annual);
fprintf('Terminal savings fixed at:   %.6f from %d\n', ...
    lrsavings_reg,year_dice(terminal_start));

tic;
[savings_decision_opt,~,regional_exitflag] = fmincon( ...
    objective,savings_guess_decision,[],[],[],[], ...
    savings_lower_decision,savings_upper_decision,[],optim_options);
regional_optimisation_minutes = toc/60;

if regional_exitflag <= 0
    warning('Interior-point returned %d; retrying with SQP.', ...
        regional_exitflag);
    optim_options = optimoptions(optim_options,'Algorithm','sqp');
    tic;
    [savings_decision_opt,~,regional_exitflag] = fmincon( ...
        objective,savings_decision_opt,[],[],[],[], ...
        savings_lower_decision,savings_upper_decision,[],optim_options);
    regional_optimisation_minutes = ...
        regional_optimisation_minutes+toc/60;
end

assert(regional_exitflag > 0, ...
    'Regional savings optimisation failed with exit flag %d.', ...
    regional_exitflag);

[savings_opt_five_year,savings_opt_annual] = ...
    build_savings_paths(savings_decision_opt,OptData);

[ ...
    K_reg_opt_annual,Ygross_reg_opt_annual,Ynet_reg_opt_annual, ...
    Inv_reg_opt_annual,C_reg_opt_annual,Welfare_reg_opt ...
    ] = simulate_regional_economy(savings_opt_annual,OptData);

OptDataNoDamage = OptData;
OptDataNoDamage.omega = zeros(H_annual,1);

[ ...
    K_reg_opt_nodamage_annual,Ygross_reg_opt_nodamage_annual,~, ...
    Inv_reg_opt_nodamage_annual,C_reg_opt_nodamage_annual, ...
    Welfare_reg_opt_nodamage ...
    ] = simulate_regional_economy( ...
    savings_opt_annual,OptDataNoDamage);

[~,savings_guess_annual] = ...
    build_savings_paths(savings_guess_decision,OptData);
[~,~,~,~,~,Welfare_reg_feasible_guess] = ...
    simulate_regional_economy(savings_guess_annual,OptData);

welfare_tolerance = 1e-8.*max(1,abs(Welfare_reg_feasible_guess));
assert(Welfare_reg_opt >= ...
    Welfare_reg_feasible_guess-welfare_tolerance, ...
    'Optimised welfare is below the feasible starting guess.');

savings_opt_block_error = check_savings_blocks( ...
    savings_opt_annual,savings_opt_five_year, ...
    five_year_idx,H_dice);
assert(savings_opt_block_error < 1e-12, ...
    'Optimised savings changes inside a five-year block.');

EconomicLoss_reg_opt_annual = ...
    Ygross_reg_opt_annual-Ynet_reg_opt_annual;
CapitalFeedbackLoss_reg_opt_annual = ...
    Ygross_reg_opt_nodamage_annual-Ygross_reg_opt_annual;
TotalOutputGap_reg_opt_annual = ...
    Ygross_reg_opt_nodamage_annual-Ynet_reg_opt_annual;

DirectDamagePctBaseline_reg_opt_annual = ...
    100.*EconomicLoss_reg_opt_annual./ ...
    Ygross_reg_opt_nodamage_annual;
CapitalFeedbackLossPct_reg_opt_annual = ...
    100.*CapitalFeedbackLoss_reg_opt_annual./ ...
    Ygross_reg_opt_nodamage_annual;
TotalOutputGapPct_reg_opt_annual = ...
    100.*TotalOutputGap_reg_opt_annual./ ...
    Ygross_reg_opt_nodamage_annual;

decomposition_error_opt = max(abs( ...
    TotalOutputGapPct_reg_opt_annual - ...
    DirectDamagePctBaseline_reg_opt_annual - ...
    CapitalFeedbackLossPct_reg_opt_annual));
assert(decomposition_error_opt < 1e-10, ...
    'The optimised loss decomposition does not balance.');

C_per_capita_reg_opt_annual = ...
    (C_reg_opt_annual./pop_annual).*1000;
CO2_reg_annual_opt = carbon_intensity_annual.* ...
    (1-abaterate_annual).*Ygross_reg_opt_annual.*ppp2mer_reg;
SavingsChangePctPoints_annual = ...
    100.*(savings_opt_annual-savings_reference_annual);

fprintf('Optimisation exit flag:     %d\n',regional_exitflag);
fprintf('Optimisation time:          %.4f minutes\n', ...
    regional_optimisation_minutes);
fprintf('Fixed-path welfare:         %.12g\n',Welfare_reg);
fprintf('Optimised welfare:          %.12g\n',Welfare_reg_opt);
fprintf('Optimised savings range:    %.4f%% to %.4f%%\n', ...
    100.*min(savings_opt_five_year), ...
    100.*max(savings_opt_five_year));

%% VALIDATION

assert(all(K_reg_annual > 0) && all(K_reg_opt_annual > 0), ...
    'Regional capital is nonpositive.');
assert(all(C_reg_annual > Params.consumption_floor) && ...
    all(C_reg_opt_annual > Params.consumption_floor), ...
    'Regional consumption reaches the utility floor.');
assert(abs(savings_opt_five_year(1)- ...
    savings_reference_five_year(1)) < 1e-12, ...
    'Optimisation does not preserve the Step B initial savings rate.');
assert(all(abs(savings_opt_five_year(terminal_start:end)- ...
    lrsavings_reg) < 1e-12), ...
    'The terminal savings tail is not fixed at the long-run rate.');
assert(all(TotalOutputGapPct_reg_opt_annual >= -1e-9), ...
    'Optimised total output gaps contain negative values.');

fprintf('\n=== STEP C VALIDATION ===\n');
fprintf('DICE temperature knot error: %.3e\n', ...
    dice_temperature_knot_error);
fprintf('DICE abatement knot error:   %.3e\n', ...
    dice_abatement_knot_error);
fprintf('SSP2 output reconstruction:  %.3e\n', ...
    baseline_output_error);
fprintf('SSP2 emissions reconstruction: %.3e\n', ...
    baseline_emissions_error);
fprintf('Fixed loss decomposition:    %.3e\n', ...
    decomposition_error_fixed);
fprintf('Optimal loss decomposition:  %.3e\n', ...
    decomposition_error_opt);

%% EXPORT ANNUAL RESULTS

regional_results = table( ...
    year_annual,T_base_annual,T_region_annual,deltaT_region_annual, ...
    BImpact_annual,omega_annual,damfrac_annual, ...
    Ybaseline_reg_ppp_annual,Ygross_reg_nodamage_annual, ...
    Ygross_reg_annual,Ynet_reg_annual, ...
    DirectDamagePctBaseline_reg_annual, ...
    CapitalFeedbackLossPct_reg_annual, ...
    TotalOutputGapPct_reg_annual,pop_annual,tfp_annual, ...
    savings_reference_annual,K_reg_nodamage_annual,K_reg_annual, ...
    Inv_reg_annual,C_reg_annual,C_per_capita_reg_annual, ...
    CO2_reg_annual,savings_opt_annual, ...
    SavingsChangePctPoints_annual,Ygross_reg_opt_nodamage_annual, ...
    Ygross_reg_opt_annual,Ynet_reg_opt_annual, ...
    DirectDamagePctBaseline_reg_opt_annual, ...
    CapitalFeedbackLossPct_reg_opt_annual, ...
    TotalOutputGapPct_reg_opt_annual,K_reg_opt_nodamage_annual, ...
    K_reg_opt_annual,Inv_reg_opt_annual,C_reg_opt_annual, ...
    C_per_capita_reg_opt_annual,CO2_reg_annual_opt, ...
    'VariableNames',{ ...
    'year','T_global','T_region_absolute','T_region_change_from_base', ...
    'regional_growth_impact','omega','damage_fraction', ...
    'Ybaseline_SSP2_PPP','Ygross_no_damage','Ygross_fixed_savings', ...
    'Ynet_fixed_savings','direct_damage_fixed_pct', ...
    'capital_feedback_fixed_pct','total_gap_fixed_pct', ...
    'population_million','tfp_annual_calibrated', ...
    'savings_rate_fixed','capital_no_damage_fixed', ...
    'capital_chronic_fixed','investment_chronic_fixed', ...
    'consumption_chronic_fixed', ...
    'consumption_per_capita_fixed_thousand_PPP', ...
    'CO2_fixed_after_global_abatement','savings_rate_optimal', ...
    'savings_change_percentage_points','Ygross_optimal_no_damage', ...
    'Ygross_optimal_chronic','Ynet_optimal_chronic', ...
    'direct_damage_optimal_pct','capital_feedback_optimal_pct', ...
    'total_gap_optimal_pct','capital_optimal_no_damage', ...
    'capital_optimal_chronic','investment_optimal_chronic', ...
    'consumption_optimal_chronic', ...
    'consumption_per_capita_optimal_thousand_PPP', ...
    'CO2_optimal_after_global_abatement'});

regional_results_file = fullfile( ...
    Params.savedir,'RCAm_regional_results_annual.csv');
writetable(regional_results,regional_results_file);

step_c_results_file = fullfile( ...
    Params.savedir,'STEP_C_annual_results.mat');

save(step_c_results_file, ...
    'Params','model_start_year','model_end_year', ...
    'year_dice','T_base_dice','abaterate_dice','H_dice', ...
    'year_annual','H_annual','five_year_idx', ...
    'T_base_annual','abaterate_annual','T_region_annual', ...
    'deltaT_region_annual','BImpact_annual','omega_annual', ...
    'damfrac_annual','Ybaseline_reg_mer_annual', ...
    'Ybaseline_reg_ppp_annual','pop_annual','tfp_annual', ...
    'tfp_input_annual','carbon_intensity_annual', ...
    'co2_baseline_annual','initial_capital_reg', ...
    'labour_share_reg','capital_share_reg','depreciation_reg', ...
    'elasmu_reg','prstp_reg','ppp2mer_reg','mer2ppp_reg', ...
    'savings_reference_five_year','savings_reference_annual', ...
    'savings_opt_five_year','savings_opt_annual', ...
    'terminal_start','terminal_constant_periods', ...
    'K_reg_nodamage_annual','Ygross_reg_nodamage_annual', ...
    'K_reg_annual','Ygross_reg_annual','Ynet_reg_annual', ...
    'Inv_reg_annual','C_reg_annual','Welfare_reg', ...
    'K_reg_opt_nodamage_annual','Ygross_reg_opt_nodamage_annual', ...
    'Inv_reg_opt_nodamage_annual','C_reg_opt_nodamage_annual', ...
    'Welfare_reg_opt_nodamage','K_reg_opt_annual', ...
    'Ygross_reg_opt_annual','Ynet_reg_opt_annual', ...
    'Inv_reg_opt_annual','C_reg_opt_annual','Welfare_reg_opt', ...
    'DirectDamagePctBaseline_reg_opt_annual', ...
    'CapitalFeedbackLossPct_reg_opt_annual', ...
    'TotalOutputGapPct_reg_opt_annual','CO2_reg_annual_opt', ...
    'baseline_output_error','baseline_emissions_error', ...
    'dice_temperature_knot_error','dice_abatement_knot_error', ...
    '-v7.3');

%% PLOTS

report_end_year = min(2250,model_end_year);
report_idx = year_annual <= report_end_year;

fig_c1 = figure('Color','w','Name','Step C Annual RCAm Effects');

plot(year_annual(report_idx), ...
    Ygross_reg_opt_nodamage_annual(report_idx),'--','LineWidth',2);
hold on;
plot(year_annual(report_idx), ...
    Ygross_reg_opt_annual(report_idx),'-','LineWidth',2);
plot(year_annual(report_idx), ...
    Ynet_reg_opt_annual(report_idx),'-','LineWidth',2.5);
xlabel('Year'); ylabel('Output (trillion 2005 PPP USD)');
title('Annual Regional Output');
legend('No damage','Gross with capital feedback', ...
    'Net after chronic impacts','Location','northwest');
grid on; box on;
export_plot_overwrite(fig_c1,plots_dir, ...
    'Figure_C1_annual_regional_output.png');


fig_c2 = figure('Color','w','Name','Step C Annual RCAm Effects');
plot(year_annual(report_idx), ...
    TotalOutputGapPct_reg_opt_annual(report_idx), ...
    'LineWidth',2.5);
hold on;
plot(year_annual(report_idx), ...
    DirectDamagePctBaseline_reg_opt_annual(report_idx),'--', ...
    'LineWidth',2);
plot(year_annual(report_idx), ...
    CapitalFeedbackLossPct_reg_opt_annual(report_idx),':', ...
    'LineWidth',2);
xlabel('Year'); ylabel('Loss relative to no damage (%)');
title('Temperature-Impact Decomposition');
legend('Total gap','Direct impact','Capital feedback', ...
    'Location','northwest');
grid on; box on;

export_plot_overwrite(fig_c2,plots_dir, ...
    'Figure_C2_annual_temperature_impacts.png');

fig_c3 = figure('Color','w','Name','Step C Savings');
policy_report_idx = 1:terminal_start-1;
policy_report_end_year = year_dice(policy_report_idx(end));

marker_idx = 1:4:numel(policy_report_idx);

plot(year_dice(policy_report_idx), ...
    100.*savings_reference_five_year(policy_report_idx), ...
    '--o','LineWidth',2, ...
    'MarkerIndices',marker_idx, ...
    'MarkerSize',4, ...
    'MarkerFaceColor','w');
hold on;
plot(year_dice(policy_report_idx), ...
    100.*savings_opt_five_year(policy_report_idx), ...
    '-o','LineWidth',2.5, ...
    'MarkerIndices',marker_idx, ...
    'MarkerSize',4, ...
    'MarkerFaceColor','w');
xlim([model_start_year policy_report_end_year]);
xlabel('Five-year decision date'); ylabel('Savings rate (%)');
title('Regional Savings Decisions');
legend('Original RCAm savings', ...
    'Savings accounting for temperature impacts', ...
    'Location','best');
grid on; box on;
export_plot_overwrite(fig_c3,plots_dir, ...
    'Figure_C3_annual_savings_optimisation.png');

fprintf('\nCompleted successfully.\n');
fprintf('Annual Step C results saved to:\n%s\n',step_c_results_file);
fprintf('Annual regional table saved to:\n%s\n',regional_results_file);

diary off;

%% LOCAL FUNCTIONS

function value = get_parameter(names,values,name)
    idx = names == lower(string(name));
    assert(nnz(idx) == 1, ...
        'Expected one RCAm parameter named "%s".',name);
    value = values(idx);
end

function err = check_savings_blocks(annual_path,node_path,node_idx,H_nodes)
    err = 0;
    for kk = 1:H_nodes-1
        block = node_idx(kk):(node_idx(kk+1)-1);
        err = max(err,max(abs(annual_path(block)-node_path(kk))));
    end
    err = max(err,abs(annual_path(end)-node_path(end)));
end

function Data = make_simulation_data( ...
    H,K0,depreciation,tfp,population,labour_share, ...
    capital_share,omega,prstp,elasmu,consumption_floor)

    Data.H = H;
    Data.initial_capital = K0;
    Data.depreciation = depreciation;
    Data.tfp = tfp;
    Data.population = population;
    Data.labour_share = labour_share;
    Data.capital_share = capital_share;
    Data.omega = omega;
    Data.discount_factor = 1./((1+prstp).^((0:H-1)'));
    Data.elasmu = elasmu;
    Data.consumption_floor = consumption_floor;
end

function objective_value = regional_savings_objective(decision,Data)
    [~,annual_path] = build_savings_paths(decision,Data);
    [~,~,~,~,~,welfare] = ...
        simulate_regional_economy(annual_path,Data);
    if isfinite(welfare)
        objective_value = -welfare;
    else
        objective_value = 1e30;
    end
end

function [node_path,annual_path] = build_savings_paths(decision,Data)
    decision = decision(:);
    assert(numel(decision) == Data.terminal_start-2, ...
        'The five-year savings decision vector has the wrong length.');

    node_path = zeros(Data.H_dice,1);
    node_path(1) = Data.savings_initial;
    node_path(2:Data.terminal_start-1) = decision;
    node_path(Data.terminal_start:end) = Data.terminal_savings;

    annual_path = node_path(Data.node_index_annual);
end

function [capital,gross_output,net_output,investment,consumption,welfare] = ...
    simulate_regional_economy(savings_path,Data)

    savings_path = savings_path(:);
    capital = zeros(Data.H,1);
    gross_output = zeros(Data.H,1);
    net_output = zeros(Data.H,1);
    investment = zeros(Data.H,1);
    consumption = zeros(Data.H,1);
    capital(1) = Data.initial_capital;
    welfare = -Inf;

    for aa = 1:Data.H
        if ~isfinite(capital(aa)) || capital(aa) <= 0
            return;
        end

        gross_output(aa) = Data.tfp(aa).* ...
            (Data.population(aa)/1000).^Data.labour_share.* ...
            capital(aa).^Data.capital_share;
        net_output(aa) = gross_output(aa)./(1+Data.omega(aa));
        investment(aa) = savings_path(aa).*net_output(aa);
        consumption(aa) = net_output(aa)-investment(aa);

        if ~isfinite(consumption(aa)) || ...
                consumption(aa) <= Data.consumption_floor
            return;
        end

        if aa < Data.H
            capital(aa+1) = ...
                (1-Data.depreciation).*capital(aa)+investment(aa);
        end
    end

    consumption_per_person = consumption./Data.population;

    if abs(Data.elasmu-1) < 1e-12
        period_utility = log(consumption_per_person);
    else
        period_utility = ...
            consumption_per_person.^(1-Data.elasmu)./(1-Data.elasmu);
    end

    welfare = sum(Data.discount_factor.* ...
        Data.population.*period_utility);
end

function export_plot_overwrite(fig,plots_dir,filename)
    output_file = fullfile(plots_dir,filename);
    if isfile(output_file)
        delete(output_file);
    end
    exportgraphics(fig,output_file,'Resolution',300);
    assert(isfile(output_file),'Plot export failed: %s',output_file);
end
