%% ========================================================================
% STEP E: SIMULATE ANNUAL STOCHASTIC HURRICANES IN THE RCAm ECONOMY
% ========================================================================
%
% Builds on the DICE-2016R-conditioned annual RCAm temperature-impact
% pathway from Step C and simulates 15,000 possible hurricane histories
% using the Jamaica hurricane calibration.
%
% Hurricane losses are applied in their realised calendar years, affecting
% output, consumption and investment immediately and carrying the resulting
% capital effects into subsequent years. The savings policy selected in
% Step C is held fixed across all simulations.
% ========================================================================

clearvars;
clc;
close all;


%% CONFIGURATION

random_seed = 6685;

[maindir,~,~] = fileparts(mfilename('fullpath'));

if isempty(maindir)
    maindir = pwd;
end

addpath(maindir);

% Number of hurricane histories used in the final analysis.
NSIMS = 15000;

rng(random_seed);

plots_dir = fullfile(maindir,'plots');

if ~exist(plots_dir,'dir')
    mkdir(plots_dir);
end

step_e_savedir = fullfile( ...
    maindir,'output','2026-07_RCAM_HURRICANE');

if ~exist(step_e_savedir,'dir')
    mkdir(step_e_savedir);
end

diary(fullfile(step_e_savedir,'Step_E_messages.txt'));


%% LOAD THE CORRECTED ANNUAL STEP C RESULTS

% Step E starts from the annual regional economy already solved in Step C.

step_c_file = fullfile( ...
    maindir,'output','2026-07_RCAM','STEP_C_annual_results.mat');

assert(isfile(step_c_file), ...
    ['Could not find the corrected Step C results: %s\n' ...
    'Run STEP_C_DICE2016R_RCAM_TEMPERATURE_IMPACTS_CORRECTED.m first.'], ...
    step_c_file);

step_c = load(step_c_file);

% Check that all the variables needed from Step C are available.
required_step_c_variables = { ...
    'Params','model_start_year','model_end_year', ...
    'year_dice','year_annual','H_annual','five_year_idx', ...
    'T_base_annual','T_region_annual','deltaT_region_annual', ...
    'BImpact_annual','omega_annual','damfrac_annual', ...
    'Ybaseline_reg_ppp_annual','pop_annual','tfp_annual', ...
    'carbon_intensity_annual','abaterate_annual', ...
    'initial_capital_reg','labour_share_reg','capital_share_reg', ...
    'depreciation_reg','elasmu_reg','prstp_reg','ppp2mer_reg', ...
    'savings_opt_annual','savings_opt_five_year', ...
    'K_reg_opt_nodamage_annual','Ygross_reg_opt_nodamage_annual', ...
    'C_reg_opt_nodamage_annual','K_reg_opt_annual', ...
    'Ygross_reg_opt_annual','Ynet_reg_opt_annual', ...
    'Inv_reg_opt_annual','C_reg_opt_annual','Welfare_reg_opt', ...
    'TotalOutputGapPct_reg_opt_annual'};

for ii = 1:numel(required_step_c_variables)

    field_name = required_step_c_variables{ii};

    assert(isfield(step_c,field_name), ...
        'Corrected Step C results are missing "%s".',field_name);

end


% Bring the Step C variables into this script.

Params = step_c.Params;
Params.savedir = step_e_savedir;
Params.consumption_floor = 1e-8;

model_start_year = step_c.model_start_year;
model_end_year = step_c.model_end_year;

year_dice = step_c.year_dice(:);
year_annual = step_c.year_annual(:);

H_annual = step_c.H_annual;
five_year_idx = step_c.five_year_idx;

T_base_annual = step_c.T_base_annual(:);
T_region_annual = step_c.T_region_annual(:);
deltaT_region_annual = step_c.deltaT_region_annual(:);

BImpact_annual = step_c.BImpact_annual(:);
omega_annual = step_c.omega_annual(:);
damfrac_annual = step_c.damfrac_annual(:);

Ybaseline_reg_ppp_annual = ...
    step_c.Ybaseline_reg_ppp_annual(:);

pop_annual = step_c.pop_annual(:);
tfp_annual = step_c.tfp_annual(:);

carbon_intensity_annual = ...
    step_c.carbon_intensity_annual(:);

abaterate_annual = ...
    step_c.abaterate_annual(:);

initial_capital_reg = step_c.initial_capital_reg;

labour_share_reg = step_c.labour_share_reg;
capital_share_reg = step_c.capital_share_reg;
depreciation_reg = step_c.depreciation_reg;

elasmu_reg = step_c.elasmu_reg;
prstp_reg = step_c.prstp_reg;
ppp2mer_reg = step_c.ppp2mer_reg;


% Savings selected in Step C after allowing for temperature impacts.
savings_policy_annual = ...
    step_c.savings_opt_annual(:);

savings_policy_five_year = ...
    step_c.savings_opt_five_year(:);


% No-damage benchmark.

K_nodamage_annual = ...
    step_c.K_reg_opt_nodamage_annual(:);

Ygross_nodamage_annual = ...
    step_c.Ygross_reg_opt_nodamage_annual(:);

C_nodamage_annual = ...
    step_c.C_reg_opt_nodamage_annual(:);


% Temperature-impact economy before hurricanes are introduced.

K_temperature_impact_annual = ...
    step_c.K_reg_opt_annual(:);

Ygross_temperature_impact_annual = ...
    step_c.Ygross_reg_opt_annual(:);

Ynet_temperature_impact_annual = ...
    step_c.Ynet_reg_opt_annual(:);

Inv_temperature_impact_annual = ...
    step_c.Inv_reg_opt_annual(:);

C_temperature_impact_annual = ...
    step_c.C_reg_opt_annual(:);

Welfare_temperature_impact = ...
    step_c.Welfare_reg_opt;

TotalOutputGapPct_temperature_impact_annual = ...
    step_c.TotalOutputGapPct_reg_opt_annual(:);


% Check that the annual pathways line up properly.

annual_lengths = [ ...
    numel(year_annual), ...
    numel(T_base_annual), ...
    numel(T_region_annual), ...
    numel(omega_annual), ...
    numel(pop_annual), ...
    numel(tfp_annual), ...
    numel(savings_policy_annual), ...
    numel(K_temperature_impact_annual), ...
    numel(Ynet_temperature_impact_annual)];

assert(all(annual_lengths == H_annual), ...
    'Step C annual pathways have inconsistent lengths.');

assert(all(diff(year_annual) == 1), ...
    'Step C regional pathways are not annual.');

assert(numel(year_dice) == numel(five_year_idx), ...
    'Step C five-year indices are inconsistent.');

assert(all(savings_policy_annual >= 0 & ...
    savings_policy_annual <= 1), ...
    'Step C savings policy lies outside [0,1].');


fprintf('\n=== STEP C ANNUAL PATHWAYS LOADED ===\n');

fprintf('Source:                   %s\n',step_c_file);

fprintf('Annual years:             %d to %d\n', ...
    year_annual(1),year_annual(end));

fprintf('Annual observations:      %d\n',H_annual);

fprintf(['Fixed savings source:     Step C savings accounting for ' ...
    'temperature impacts\n']);


%% LOAD JAMAICA HURRICANE CALIBRATION

% Load the annual Jamaica hurricane rate, Atlantic category probabilities
% and category-specific loss shares produced in Step D.

hurricane_parameter_file = fullfile( ...
    maindir,'calibrated_hurricane_params.mat');

assert(isfile(hurricane_parameter_file), ...
    'Could not find hurricane calibration: %s', ...
    hurricane_parameter_file);

hurricane_calibration = ...
    load(hurricane_parameter_file);


% Check that the Step D calibration contains the required inputs.

required_hurricane_fields = { ...
    'lambda_jamaica', ...
    'p_cat_jamaica_proxy', ...
    'hurricane_loss_share_by_cat', ...
    'target_aal_baseline'};

for ii = 1:numel(required_hurricane_fields)

    field_name = required_hurricane_fields{ii};

    assert(isfield(hurricane_calibration,field_name), ...
        'Hurricane calibration is missing "%s".',field_name);

end


% Jamaica annual hurricane frequency.

local_rate = ...
    double(hurricane_calibration.lambda_jamaica);


% Atlantic category distribution used as the Jamaica severity proxy.

cat_probs = double( ...
    hurricane_calibration.p_cat_jamaica_proxy(:)');


% Output-equivalent loss assigned to each hurricane category.

hurricane_loss_share_by_cat = double( ...
    hurricane_calibration.hurricane_loss_share_by_cat(:)');


% Expected annual loss used when calibrating the category losses.

calibration_target_aal = double( ...
    hurricane_calibration.target_aal_baseline);


% Atlantic rate is retained for reporting only.

if isfield(hurricane_calibration,'lambda_atlantic')

    basin_rate = ...
        double(hurricane_calibration.lambda_atlantic);

else

    basin_rate = NaN;

end


% Basic hurricane calibration checks.

assert(isscalar(local_rate) && ...
    isfinite(local_rate) && ...
    local_rate >= 0, ...
    'lambda_jamaica must be a finite nonnegative scalar.');

assert(numel(cat_probs) == 5 && ...
    all(isfinite(cat_probs)) && ...
    all(cat_probs >= 0) && ...
    sum(cat_probs) > 0, ...
    'Hurricane category probabilities are invalid.');

assert(numel(hurricane_loss_share_by_cat) == 5 && ...
    all(isfinite(hurricane_loss_share_by_cat)) && ...
    all(hurricane_loss_share_by_cat >= 0) && ...
    all(hurricane_loss_share_by_cat < 1), ...
    'Hurricane loss shares must lie in [0,1).');

cat_probs = ...
    cat_probs./sum(cat_probs);


%% TEMPERATURE-DEPENDENT HURRICANE INTENSITY

% Hurricane frequency stays fixed. Warming only changes the mix of storm
% categories by shifting some probability towards Categories 4 and 5.
%
% The combined Category 4-5 probability rises by 13% for every 2 degrees C
% of regional warming relative to 2015.

temperature_intensity_reference = ...
    T_region_annual(1);

intensity_temperature_change = max( ...
    T_region_annual-temperature_intensity_reference,0);

cat45_relative_change_at_2C = 0.13;

cat45_relative_change_per_degree = ...
    cat45_relative_change_at_2C/2;


% Separate non-major and major hurricane probabilities.

baseline_nonmajor_probability = ...
    sum(cat_probs(1:3));

baseline_major_probability = ...
    sum(cat_probs(4:5));

assert(baseline_nonmajor_probability > 0 && ...
    baseline_major_probability > 0, ...
    'Both nonmajor and major baseline probabilities must be positive.');


% Increase the Cat 4-5 share as regional temperature rises.

major_probability_annual = ...
    baseline_major_probability.*( ...
    1+cat45_relative_change_per_degree.* ...
    intensity_temperature_change);

major_probability_annual = ...
    min(major_probability_annual,0.999999);

nonmajor_probability_annual = ...
    1-major_probability_annual;


% Keep the relative split within Cats 1-3 and Cats 4-5 unchanged.

cat_probs_annual = ...
    zeros(H_annual,5);

cat_probs_annual(:,1:3) = ...
    nonmajor_probability_annual.* ...
    (cat_probs(1:3)./baseline_nonmajor_probability);

cat_probs_annual(:,4:5) = ...
    major_probability_annual.* ...
    (cat_probs(4:5)./baseline_major_probability);

cat_probs_annual = ...
    cat_probs_annual./sum(cat_probs_annual,2);


% CDF used later when drawing a category for each simulated storm.

cat_cdf_annual = ...
    cumsum(cat_probs_annual,2);

cat_cdf_annual(:,5) = 1;


assert(all(cat_probs_annual(:) >= 0) && ...
    all(abs(sum(cat_probs_annual,2)-1) < 1e-12), ...
    'Annual category probabilities are invalid.');


% Check the expected annual loss implied by the calibration.

conditional_mean_event_loss = ...
    sum(cat_probs.*hurricane_loss_share_by_cat);

expected_annual_loss_linear = ...
    local_rate.*conditional_mean_event_loss;

expected_annual_loss_compound = ...
    1-exp(-expected_annual_loss_linear);


% The expected loss changes slightly over time because the category mix
% becomes more severe with regional warming.

conditional_mean_event_loss_annual = ...
    cat_probs_annual*hurricane_loss_share_by_cat';

expected_annual_loss_linear_annual = ...
    local_rate.*conditional_mean_event_loss_annual;

expected_annual_loss_compound_annual = ...
    1-exp(-expected_annual_loss_linear_annual);

expected_horizon_mean_annual_loss = ...
    mean(expected_annual_loss_compound_annual);


% The baseline calibration should still reproduce the Step D AAL target.

assert(abs( ...
    expected_annual_loss_linear-calibration_target_aal) < 1e-10, ...
    ['Loaded hurricane losses do not reproduce the calibration target. ' ...
    'Rerun the hurricane calibration.']);


fprintf('\n=== HURRICANE CALIBRATION ===\n');

fprintf('Atlantic annual rate:       %.6f\n', ...
    basin_rate);

fprintf('Jamaica annual rate:        %.6f\n', ...
    local_rate);

fprintf('Category probabilities:     %s\n', ...
    mat2str(cat_probs,6));

fprintf('Category loss shares:       %s\n', ...
    mat2str(hurricane_loss_share_by_cat,6));

fprintf('Expected annual loss:       %.4f%%\n', ...
    100.*expected_annual_loss_compound);


%% MONTE CARLO INITIALISATION

% Preallocate the main simulation arrays.
% Rows are years and columns are hurricane histories.

assert(exist('poissrnd','file') == 2, ...
    ['Step E requires poissrnd from the Statistics and ' ...
    'Machine Learning Toolbox.']);


K_hurr_stoch = ...
    zeros(H_annual,NSIMS);

Ygross_hurr_stoch = ...
    zeros(H_annual,NSIMS);

EIND_hurr_stoch = ...
    zeros(H_annual,NSIMS);

Ynet_temperature_sameK_stoch = ...
    zeros(H_annual,NSIMS);

Ynet_hurr_stoch = ...
    zeros(H_annual,NSIMS);

Investment_hurr_stoch = ...
    zeros(H_annual,NSIMS);

Consumption_hurr_stoch = ...
    zeros(H_annual,NSIMS);


HurricaneAnnualLossShare_stoch = ...
    zeros(H_annual,NSIMS);

HurricaneAdditionalLossPct_stoch = ...
    zeros(H_annual,NSIMS);

TotalOutputGapPct_hurr_stoch = ...
    zeros(H_annual,NSIMS);


% Draw the number of hurricanes occurring in every year of every history.

NumHurricanesAnnual_stoch = uint16( ...
    poissrnd(local_rate,H_annual,NSIMS));


% Store how many Cat 1, 2, 3, 4 and 5 storms occur in each year.

CategoryCountsAnnual_stoch = ...
    zeros(H_annual,NSIMS,5,'uint16');


Welfare_hurr_stoch = ...
    zeros(NSIMS,1);


% Every simulation begins with the same initial RCAm capital stock.

K_hurr_stoch(1,:) = ...
    initial_capital_reg;


fprintf('\n=== MONTE CARLO SETTINGS ===\n');

fprintf('Simulations:               %d\n',NSIMS);

fprintf('Annual decision periods:   %d\n',H_annual);

fprintf('Expected events per year:  %.6f\n', ...
    local_rate);

fprintf('Event probability per year: %.4f%%\n', ...
    100.*(1-exp(-local_rate)));


%% RUN ANNUAL HURRICANE SIMULATIONS

% Work through the regional economy one year at a time.
% Hurricanes affect the year in which they occur. The lower investment that
% follows from the output loss then affects the capital stock in later years.

for aa = 1:H_annual

    % Only simulations containing a hurricane need category draws.
    affected_sims = ...
        find(NumHurricanesAnnual_stoch(aa,:) > 0);


    for jj = 1:numel(affected_sims)

        sim = affected_sims(jj);

        n_events = ...
            double(NumHurricanesAnnual_stoch(aa,sim));


        % Draw a category for each hurricane using that year's probabilities.
        u = rand(n_events,1);

        category_index = ...
            1+sum(u > cat_cdf_annual(aa,:),2);


        % Convert the categories into the calibrated loss shares.
        event_losses = ...
            hurricane_loss_share_by_cat(category_index);


        % If more than one storm occurs in a year, losses are compounded
        % rather than averaged.
        HurricaneAnnualLossShare_stoch(aa,sim) = ...
            1-prod(1-event_losses);


        % Record how many storms occurred in each category.
        category_counts = ...
            accumarray(category_index,1,[5 1]);

        CategoryCountsAnnual_stoch(aa,sim,:) = ...
            reshape(uint16(category_counts),1,1,5);

    end


    % Gross output is determined using the capital available at the start
    % of the current year.
    Ygross_hurr_stoch(aa,:) = ...
        tfp_annual(aa).* ...
        (pop_annual(aa)/1000).^labour_share_reg.* ...
        K_hurr_stoch(aa,:).^capital_share_reg;


    % Regional emissions are derived from gross output and the fixed global
    % DICE abatement pathway.
    EIND_hurr_stoch(aa,:) = ...
        carbon_intensity_annual(aa).* ...
        (1-abaterate_annual(aa)).* ...
        Ygross_hurr_stoch(aa,:).* ...
        ppp2mer_reg;


    % First apply the chronic regional temperature impact.
    Ynet_temperature_sameK_stoch(aa,:) = ...
        Ygross_hurr_stoch(aa,:)./(1+omega_annual(aa));


    % Then apply the realised hurricane loss in that calendar year.
    Ynet_hurr_stoch(aa,:) = ...
        Ynet_temperature_sameK_stoch(aa,:).* ...
        (1-HurricaneAnnualLossShare_stoch(aa,:));


    % Additional output loss caused by hurricanes alone.
    HurricaneAdditionalLossPct_stoch(aa,:) = ...
        100.*( ...
        1-Ynet_hurr_stoch(aa,:)./ ...
        Ynet_temperature_sameK_stoch(aa,:));


    % Savings remains fixed at the Step C pathway.
    Investment_hurr_stoch(aa,:) = ...
        savings_policy_annual(aa).* ...
        Ynet_hurr_stoch(aa,:);


    Consumption_hurr_stoch(aa,:) = ...
        Ynet_hurr_stoch(aa,:)- ...
        Investment_hurr_stoch(aa,:);


    % Keep consumption positive if an extreme simulated loss pushes it
    % below the numerical floor.
    low_consumption = ...
        Consumption_hurr_stoch(aa,:) <= ...
        Params.consumption_floor;


    if any(low_consumption)

        Consumption_hurr_stoch(aa,low_consumption) = ...
            Params.consumption_floor;

        Investment_hurr_stoch(aa,low_consumption) = max( ...
            Ynet_hurr_stoch(aa,low_consumption)- ...
            Params.consumption_floor,0);

    end


    % Total output gap relative to the no-temperature-impact,
    % no-hurricane economy.
    TotalOutputGapPct_hurr_stoch(aa,:) = ...
        100.*( ...
        Ygross_nodamage_annual(aa)- ...
        Ynet_hurr_stoch(aa,:))./ ...
        Ygross_nodamage_annual(aa);


    % Today's investment contributes to next year's capital stock.
    if aa < H_annual

        K_hurr_stoch(aa+1,:) = ...
            (1-depreciation_reg).* ...
            K_hurr_stoch(aa,:) + ...
            Investment_hurr_stoch(aa,:);

    end

end


%% CALCULATE WELFARE

% Calculate welfare separately for each complete hurricane history.

discfactor_reg_annual = ...
    1./((1+prstp_reg).^((0:H_annual-1)'));


for sim = 1:NSIMS

    consumption_per_person = ...
        Consumption_hurr_stoch(:,sim)./ ...
        pop_annual;


    if abs(elasmu_reg-1) < 1e-12

        utility_hurr_sim = ...
            log(consumption_per_person);

    else

        utility_hurr_sim = ...
            consumption_per_person.^(1-elasmu_reg)./ ...
            (1-elasmu_reg);

    end


    Welfare_hurr_stoch(sim) = ...
        sum( ...
        discfactor_reg_annual.* ...
        pop_annual.* ...
        utility_hurr_sim);

end


%% VALIDATE ANNUAL SIMULATIONS

% Basic checks to make sure the simulated paths are valid and that
% hurricane counts and losses have been applied correctly.

assert(all(isfinite(Ynet_hurr_stoch),'all') && ...
    all(Ynet_hurr_stoch > 0,'all'), ...
    'Hurricane output is invalid.');

assert(all(Consumption_hurr_stoch > 0,'all'), ...
    'Hurricane consumption is nonpositive.');

assert(all(K_hurr_stoch > 0,'all'), ...
    'Hurricane capital is nonpositive.');

assert(all(HurricaneAnnualLossShare_stoch >= 0,'all') && ...
    all(HurricaneAnnualLossShare_stoch < 1,'all'), ...
    'An annual hurricane loss lies outside [0,1).');


% Number of assigned categories should equal number of simulated storms.

category_count_error = max(abs( ...
    double(sum(CategoryCountsAnnual_stoch,3))- ...
    double(NumHurricanesAnnual_stoch)), ...
    [],'all');

assert(category_count_error == 0, ...
    'Annual category counts do not equal annual event counts.');


% The percentage loss calculated from output should match the hurricane
% loss share applied to output.

loss_application_error = max(abs( ...
    HurricaneAdditionalLossPct_stoch./100 - ...
    HurricaneAnnualLossShare_stoch), ...
    [],'all');

assert(loss_application_error < 1e-8, ...
    'Hurricane losses were not applied in the event year.');


% Adding a hurricane should never raise output above the Step C
% temperature-impact pathway.

max_hurricane_output_violation = max( ...
    Ynet_hurr_stoch- ...
    repmat(Ynet_temperature_impact_annual,1,NSIMS), ...
    [],'all');

assert(max_hurricane_output_violation < 1e-8, ...
    'A hurricane pathway exceeds the Step C temperature-impact pathway.');


%% SUMMARY DISTRIBUTIONS

% Summarise the 15,000 simulated histories at each year.
% These percentiles are year-specific outcomes, not individual paths.

Ynet_hurr_mean = ...
    mean(Ynet_hurr_stoch,2);

Ynet_hurr_q05 = ...
    quantile(Ynet_hurr_stoch',0.05)';

Ynet_hurr_q25 = ...
    quantile(Ynet_hurr_stoch',0.25)';

Ynet_hurr_q50 = ...
    quantile(Ynet_hurr_stoch',0.50)';

Ynet_hurr_q75 = ...
    quantile(Ynet_hurr_stoch',0.75)';

Ynet_hurr_q95 = ...
    quantile(Ynet_hurr_stoch',0.95)';


K_hurr_mean = ...
    mean(K_hurr_stoch,2);

K_hurr_q05 = ...
    quantile(K_hurr_stoch',0.05)';

K_hurr_q50 = ...
    quantile(K_hurr_stoch',0.50)';

K_hurr_q95 = ...
    quantile(K_hurr_stoch',0.95)';


Consumption_hurr_mean = ...
    mean(Consumption_hurr_stoch,2);

Consumption_hurr_q05 = ...
    quantile(Consumption_hurr_stoch',0.05)';

Consumption_hurr_q50 = ...
    quantile(Consumption_hurr_stoch',0.50)';

Consumption_hurr_q95 = ...
    quantile(Consumption_hurr_stoch',0.95)';


EIND_hurr_mean = ...
    mean(EIND_hurr_stoch,2);

EIND_hurr_q05 = ...
    quantile(EIND_hurr_stoch',0.05)';

EIND_hurr_q50 = ...
    quantile(EIND_hurr_stoch',0.50)';

EIND_hurr_q95 = ...
    quantile(EIND_hurr_stoch',0.95)';


HurricaneAdditionalLossPct_mean = ...
    mean(HurricaneAdditionalLossPct_stoch,2);

HurricaneAdditionalLossPct_q50 = ...
    quantile(HurricaneAdditionalLossPct_stoch',0.50)';

HurricaneAdditionalLossPct_q95 = ...
    quantile(HurricaneAdditionalLossPct_stoch',0.95)';

HurricaneAdditionalLossPct_q99 = ...
    quantile(HurricaneAdditionalLossPct_stoch',0.99)';


TotalOutputGapPct_hurr_mean = ...
    mean(TotalOutputGapPct_hurr_stoch,2);

TotalOutputGapPct_hurr_q50 = ...
    quantile(TotalOutputGapPct_hurr_stoch',0.50)';

TotalOutputGapPct_hurr_q95 = ...
    quantile(TotalOutputGapPct_hurr_stoch',0.95)';

TotalOutputGapPct_hurr_q99 = ...
    quantile(TotalOutputGapPct_hurr_stoch',0.99)';


% Hurricane occurrence summaries.

NumHurricanes_mean = ...
    mean(NumHurricanesAnnual_stoch,2);

ProbabilityAnyHurricaneByYear = ...
    mean(NumHurricanesAnnual_stoch > 0,2);

ProbabilityCat5ByYear = ...
    mean(CategoryCountsAnnual_stoch(:,:,5) > 0,2);

MeanCategoryCountsByYear = ...
    squeeze(mean(CategoryCountsAnnual_stoch,2));


% Check realised category distribution across all simulated storms.

total_category_counts = ...
    squeeze(sum( ...
    sum(CategoryCountsAnnual_stoch,1),2));

total_simulated_events = ...
    sum(total_category_counts);


if total_simulated_events > 0

    realised_category_probabilities = ...
        total_category_counts./ ...
        total_simulated_events;

else

    realised_category_probabilities = ...
        NaN(5,1);

end


% Welfare distribution.

Welfare_hurr_mean = ...
    mean(Welfare_hurr_stoch);

Welfare_hurr_q05 = ...
    quantile(Welfare_hurr_stoch,0.05);

Welfare_hurr_q50 = ...
    quantile(Welfare_hurr_stoch,0.50);

Welfare_hurr_q95 = ...
    quantile(Welfare_hurr_stoch,0.95);


% Overall Monte Carlo checks.

realised_mean_events_per_year = ...
    mean(NumHurricanesAnnual_stoch,'all');

realised_probability_event_annual = ...
    mean(NumHurricanesAnnual_stoch > 0,'all');

realised_mean_annual_loss = ...
    mean(HurricaneAnnualLossShare_stoch,'all');

annual_loss_calibration_error = ...
    realised_mean_annual_loss- ...
    expected_horizon_mean_annual_loss;


fprintf('\n=== STEP E RESULTS ===\n');

fprintf('Mean events per year:       %.6f\n', ...
    realised_mean_events_per_year);

fprintf('Annual event probability:   %.4f%%\n', ...
    100.*realised_probability_event_annual);

fprintf('Expected annual loss:       %.4f%%\n', ...
    100.*expected_horizon_mean_annual_loss);

fprintf('Realised annual loss:       %.4f%%\n', ...
    100.*realised_mean_annual_loss);

fprintf('Step C temperature-impact welfare: %.12g\n', ...
    Welfare_temperature_impact);

fprintf('Mean hurricane welfare:     %.12g\n', ...
    Welfare_hurr_mean);

fprintf('Loss application error:     %.3e\n', ...
    loss_application_error);


%% EXPORT ANNUAL SUMMARY TABLE

% Save the annual Monte Carlo summaries in one CSV.

regional_hurricane_results = table( ...
    year_annual, ...
    T_base_annual, ...
    T_region_annual, ...
    deltaT_region_annual, ...
    BImpact_annual, ...
    omega_annual, ...
    damfrac_annual, ...
    Ygross_nodamage_annual, ...
    Ygross_temperature_impact_annual, ...
    Ynet_temperature_impact_annual, ...
    TotalOutputGapPct_temperature_impact_annual, ...
    Ynet_hurr_mean, ...
    Ynet_hurr_q05, ...
    Ynet_hurr_q25, ...
    Ynet_hurr_q50, ...
    Ynet_hurr_q75, ...
    Ynet_hurr_q95, ...
    K_hurr_mean, ...
    K_hurr_q05, ...
    K_hurr_q50, ...
    K_hurr_q95, ...
    Consumption_hurr_mean, ...
    Consumption_hurr_q05, ...
    Consumption_hurr_q50, ...
    Consumption_hurr_q95, ...
    HurricaneAdditionalLossPct_mean, ...
    HurricaneAdditionalLossPct_q50, ...
    HurricaneAdditionalLossPct_q95, ...
    HurricaneAdditionalLossPct_q99, ...
    TotalOutputGapPct_hurr_mean, ...
    TotalOutputGapPct_hurr_q50, ...
    TotalOutputGapPct_hurr_q95, ...
    TotalOutputGapPct_hurr_q99, ...
    EIND_hurr_mean, ...
    EIND_hurr_q05, ...
    EIND_hurr_q50, ...
    EIND_hurr_q95, ...
    NumHurricanes_mean, ...
    ProbabilityAnyHurricaneByYear, ...
    ProbabilityCat5ByYear, ...
    MeanCategoryCountsByYear(:,1), ...
    MeanCategoryCountsByYear(:,2), ...
    MeanCategoryCountsByYear(:,3), ...
    MeanCategoryCountsByYear(:,4), ...
    MeanCategoryCountsByYear(:,5), ...
    pop_annual, ...
    tfp_annual, ...
    savings_policy_annual, ...
    K_nodamage_annual, ...
    K_temperature_impact_annual, ...
    C_temperature_impact_annual, ...
    'VariableNames',{ ...
    'year', ...
    'T_global', ...
    'T_region_absolute', ...
    'T_region_change_from_base', ...
    'regional_growth_impact', ...
    'omega', ...
    'damage_fraction', ...
    'Ygross_no_damage', ...
    'Ygross_with_temperature_impacts', ...
    'Ynet_with_temperature_impacts', ...
    'temperature_impact_gap_pct', ...
    'Ynet_hurricane_mean', ...
    'Ynet_hurricane_5th_percentile', ...
    'Ynet_hurricane_25th_percentile', ...
    'Ynet_hurricane_median', ...
    'Ynet_hurricane_75th_percentile', ...
    'Ynet_hurricane_95th_percentile', ...
    'capital_hurricane_mean', ...
    'capital_hurricane_5th_percentile', ...
    'capital_hurricane_median', ...
    'capital_hurricane_95th_percentile', ...
    'consumption_hurricane_mean', ...
    'consumption_hurricane_5th_percentile', ...
    'consumption_hurricane_median', ...
    'consumption_hurricane_95th_percentile', ...
    'additional_hurricane_loss_mean_pct', ...
    'additional_hurricane_loss_median_pct', ...
    'additional_hurricane_loss_95th_percentile_pct', ...
    'additional_hurricane_loss_99th_percentile_pct', ...
    'total_gap_hurricane_mean_pct', ...
    'total_gap_hurricane_median_pct', ...
    'total_gap_hurricane_95th_percentile_pct', ...
    'total_gap_hurricane_99th_percentile_pct', ...
    'regional_emissions_hurricane_mean', ...
    'regional_emissions_hurricane_5th_percentile', ...
    'regional_emissions_hurricane_median', ...
    'regional_emissions_hurricane_95th_percentile', ...
    'mean_hurricanes_per_year', ...
    'probability_any_hurricane', ...
    'probability_cat5', ...
    'mean_cat1_events', ...
    'mean_cat2_events', ...
    'mean_cat3_events', ...
    'mean_cat4_events', ...
    'mean_cat5_events', ...
    'population_million', ...
    'tfp_annual_calibrated', ...
    'savings_rate_accounting_for_temperature_impacts', ...
    'capital_no_damage', ...
    'capital_with_temperature_impacts', ...
    'consumption_with_temperature_impacts'});


% Add the expected hurricane probabilities used in each year.

regional_hurricane_results.expected_cat1_probability = ...
    cat_probs_annual(:,1);

regional_hurricane_results.expected_cat2_probability = ...
    cat_probs_annual(:,2);

regional_hurricane_results.expected_cat3_probability = ...
    cat_probs_annual(:,3);

regional_hurricane_results.expected_cat4_probability = ...
    cat_probs_annual(:,4);

regional_hurricane_results.expected_cat5_probability = ...
    cat_probs_annual(:,5);

regional_hurricane_results.expected_major_probability = ...
    major_probability_annual;

regional_hurricane_results.expected_annual_loss_pct = ...
    100.*expected_annual_loss_compound_annual;


regional_hurricane_results_file = fullfile( ...
    Params.savedir, ...
    'RCAm_hurricane_results_annual.csv');

writetable( ...
    regional_hurricane_results, ...
    regional_hurricane_results_file);


%% SAVE MONTE CARLO RESULTS

% Save the full arrays because Step F needs the individual hurricane
% histories rather than only the summary statistics.

hurricane_monte_carlo_file = fullfile( ...
    Params.savedir, ...
    'RCAm_hurricane_MonteCarlo_annual.mat');


save(hurricane_monte_carlo_file, ...
    'Params', ...
    'NSIMS', ...
    'model_start_year', ...
    'model_end_year', ...
    'year_dice', ...
    'year_annual', ...
    'H_annual', ...
    'five_year_idx', ...
    'T_base_annual', ...
    'T_region_annual', ...
    'deltaT_region_annual', ...
    'BImpact_annual', ...
    'omega_annual', ...
    'damfrac_annual', ...
    'Ybaseline_reg_ppp_annual', ...
    'pop_annual', ...
    'tfp_annual', ...
    'carbon_intensity_annual', ...
    'abaterate_annual', ...
    'initial_capital_reg', ...
    'labour_share_reg', ...
    'capital_share_reg', ...
    'depreciation_reg', ...
    'elasmu_reg', ...
    'prstp_reg', ...
    'ppp2mer_reg', ...
    'savings_policy_five_year', ...
    'savings_policy_annual', ...
    'K_nodamage_annual', ...
    'Ygross_nodamage_annual', ...
    'C_nodamage_annual', ...
    'K_temperature_impact_annual', ...
    'Ygross_temperature_impact_annual', ...
    'Ynet_temperature_impact_annual', ...
    'Inv_temperature_impact_annual', ...
    'C_temperature_impact_annual', ...
    'Welfare_temperature_impact', ...
    'local_rate', ...
    'basin_rate', ...
    'cat_probs', ...
    'cat_probs_annual', ...
    'cat_cdf_annual', ...
    'major_probability_annual', ...
    'hurricane_loss_share_by_cat', ...
    'calibration_target_aal', ...
    'expected_annual_loss_linear_annual', ...
    'expected_annual_loss_compound_annual', ...
    'K_hurr_stoch', ...
    'Ygross_hurr_stoch', ...
    'EIND_hurr_stoch', ...
    'Ynet_temperature_sameK_stoch', ...
    'Ynet_hurr_stoch', ...
    'Investment_hurr_stoch', ...
    'Consumption_hurr_stoch', ...
    'HurricaneAnnualLossShare_stoch', ...
    'HurricaneAdditionalLossPct_stoch', ...
    'TotalOutputGapPct_hurr_stoch', ...
    'NumHurricanesAnnual_stoch', ...
    'CategoryCountsAnnual_stoch', ...
    'Welfare_hurr_stoch', ...
    'realised_category_probabilities', ...
    'realised_mean_events_per_year', ...
    'realised_probability_event_annual', ...
    'realised_mean_annual_loss', ...
    'annual_loss_calibration_error', ...
    'loss_application_error', ...
    '-v7.3');


%% PLOTS

report_end_year = ...
    min(2250,model_end_year);

report_idx = ...
    year_annual <= report_end_year;

plot_year = ...
    year_annual(report_idx);


%% FIGURE E1: ANNUAL OUTPUT LOSS

% Compare the temperature-impact pathway with the average and median
% outcomes once hurricanes are included.

fig_e1 = figure( ...
    'Color','w', ...
    'Name','Step E Annual Hurricane Loss');


plot( ...
    plot_year, ...
    TotalOutputGapPct_temperature_impact_annual(report_idx), ...
    '--', ...
    'LineWidth',2);

hold on;


plot( ...
    plot_year, ...
    TotalOutputGapPct_hurr_mean(report_idx), ...
    '-', ...
    'LineWidth',2.5);


plot( ...
    plot_year, ...
    TotalOutputGapPct_hurr_q50(report_idx), ...
    '-.', ...
    'LineWidth',1.75);


xlabel('Year');

ylabel('Loss relative to no damage (%)');

title('Annual Regional Output Loss');


legend( ...
    'Temperature impacts only', ...
    'Mean with hurricanes', ...
    'Median with hurricanes', ...
    'Location','northwest');

grid on;
box on;


export_plot_overwrite( ...
    fig_e1, ...
    plots_dir, ...
    'Figure_E1_annual_hurricane_output_loss.png');


%% FIGURE E2: SELECTED-YEAR OUTPUT LOSSES

% These percentiles are separate outcomes calculated at each year.
% They are shown as selected-year points rather than connected as though
% they were one simulated hurricane path.

benchmark_years = ...
    [2050;2100;2150;2200;2250];


[benchmark_found,benchmark_idx] = ...
    ismember(benchmark_years,year_annual);

assert(all(benchmark_found), ...
    'A selected benchmark year is outside the annual model horizon.');


output_loss_95 = ...
    TotalOutputGapPct_hurr_q95(benchmark_idx);

output_loss_99 = ...
    TotalOutputGapPct_hurr_q99(benchmark_idx);


blue_colour = ...
    [0.0000 0.4470 0.7410];

orange_colour = ...
    [0.8500 0.3250 0.0980];

joining_colour = ...
    [0.70 0.70 0.70];


fig_e2 = figure( ...
    'Color','w', ...
    'Name','Step E Tail Output Losses');

hold on;


% Join the 95th and 99th percentile values within each selected year.

for kk = 1:numel(benchmark_years)

    plot( ...
        [benchmark_years(kk) benchmark_years(kk)], ...
        [output_loss_95(kk) output_loss_99(kk)], ...
        '-', ...
        'Color',joining_colour, ...
        'LineWidth',1.5, ...
        'HandleVisibility','off');

end


h95 = plot( ...
    benchmark_years, ...
    output_loss_95, ...
    'o', ...
    'LineStyle','none', ...
    'MarkerSize',9, ...
    'MarkerFaceColor',blue_colour, ...
    'MarkerEdgeColor',blue_colour, ...
    'LineWidth',1.5);


h99 = plot( ...
    benchmark_years, ...
    output_loss_99, ...
    'd', ...
    'LineStyle','none', ...
    'MarkerSize',9, ...
    'MarkerFaceColor',orange_colour, ...
    'MarkerEdgeColor',orange_colour, ...
    'LineWidth',1.5);


xlabel('Year');

ylabel('Loss relative to no damage (%)');

title('Severe Hurricane Output Losses at Selected Years');


xticks(benchmark_years);

xlim([2035 2265]);

ylim([0 1.10.*max(output_loss_99)]);


legend( ...
    [h95 h99], ...
    '95th-percentile loss', ...
    '99th-percentile loss', ...
    'Location','northwest');

grid on;
box on;


export_plot_overwrite( ...
    fig_e2, ...
    plots_dir, ...
    'Figure_E2_selected_year_tail_losses.png');


%%CALCULATE CAPITAL AND CONSUMPTION SHORTFALLS

% Convert the capital and consumption outcomes into percentage shortfalls
% relative to the no-damage economy.

CapitalGapTemperaturePct = ...
    100.*( ...
    K_nodamage_annual- ...
    K_temperature_impact_annual)./ ...
    K_nodamage_annual;


CapitalGapHurricaneMeanPct = ...
    100.*( ...
    K_nodamage_annual- ...
    K_hurr_mean)./ ...
    K_nodamage_annual;


% Low capital is equivalent to a high capital shortfall.
CapitalGapHurricaneP95Pct = ...
    100.*( ...
    K_nodamage_annual- ...
    K_hurr_q05)./ ...
    K_nodamage_annual;


ConsumptionGapTemperaturePct = ...
    100.*( ...
    C_nodamage_annual- ...
    C_temperature_impact_annual)./ ...
    C_nodamage_annual;


ConsumptionGapHurricaneMeanPct = ...
    100.*( ...
    C_nodamage_annual- ...
    Consumption_hurr_mean)./ ...
    C_nodamage_annual;


% Low consumption is equivalent to a high consumption shortfall.
ConsumptionGapHurricaneP95Pct = ...
    100.*( ...
    C_nodamage_annual- ...
    Consumption_hurr_q05)./ ...
    C_nodamage_annual;


%% APPENDIX E1: ANNUAL CAPITAL AND CONSUMPTION EFFECTS

% Compare temperature impacts alone with the average result after adding
% stochastic hurricanes.

fig_appendix_e1 = figure( ...
    'Color','w', ...
    'Name','Step E Capital and Consumption');


tiledlayout( ...
    1,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');


%%Capital

nexttile;
plot( ...
    plot_year, ...
    CapitalGapTemperaturePct(report_idx), ...
    '--', ...
    'LineWidth',2);

hold on;

plot( ...
    plot_year, ...
    CapitalGapHurricaneMeanPct(report_idx), ...
    '-', ...
    'LineWidth',2.5);

xlabel('Year');
ylabel('Shortfall relative to no damage (%)');
title('Capital Shortfall');

legend( ...
    'Temperature impacts only', ...
    'Mean with hurricanes', ...
    'Location','northwest');

grid on;
box on;


%%Consumption
nexttile;

plot( ...
    plot_year, ...
    ConsumptionGapTemperaturePct(report_idx), ...
    '--', ...
    'LineWidth',2);

hold on;

plot( ...
    plot_year, ...
    ConsumptionGapHurricaneMeanPct(report_idx), ...
    '-', ...
    'LineWidth',2.5);

xlabel('Year');
ylabel('Shortfall relative to no damage (%)');
title('Consumption Shortfall');
legend( ...
    'Temperature impacts only', ...
    'Mean with hurricanes', ...
    'Location','northwest');

grid on;
box on;
sgtitle('Annual Capital and Consumption Effects');
export_plot_overwrite( ...
    fig_appendix_e1, ...
    plots_dir, ...
    'Appendix_E1_annual_capital_consumption_shortfalls.png');


%% APPENDIX E2: SELECTED-YEAR CAPITAL AND CONSUMPTION EFFECTS

% Compare the mean shortfall with a more severe 95th-percentile shortfall
% at the selected benchmark years.

capital_mean = ...
    CapitalGapHurricaneMeanPct(benchmark_idx);

capital_95 = ...
    CapitalGapHurricaneP95Pct(benchmark_idx);

consumption_mean = ...
    ConsumptionGapHurricaneMeanPct(benchmark_idx);

consumption_95 = ...
    ConsumptionGapHurricaneP95Pct(benchmark_idx);


fig_appendix_e2 = figure( ...
    'Color','w', ...
    'Name','Step E Selected-Year Tail Shortfalls');


tiledlayout( ...
    1,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');


%%Capital shortfall

nexttile;
hold on;

for kk = 1:numel(benchmark_years)

    plot( ...
        [benchmark_years(kk) benchmark_years(kk)], ...
        [capital_mean(kk) capital_95(kk)], ...
        '-', ...
        'Color',joining_colour, ...
        'LineWidth',1.5, ...
        'HandleVisibility','off');

end


h_capital_mean = plot( ...
    benchmark_years, ...
    capital_mean, ...
    'o', ...
    'LineStyle','none', ...
    'MarkerSize',9, ...
    'MarkerFaceColor',blue_colour, ...
    'MarkerEdgeColor',blue_colour, ...
    'LineWidth',1.5);


h_capital_95 = plot( ...
    benchmark_years, ...
    capital_95, ...
    'd', ...
    'LineStyle','none', ...
    'MarkerSize',9, ...
    'MarkerFaceColor',orange_colour, ...
    'MarkerEdgeColor',orange_colour, ...
    'LineWidth',1.5);


xlabel('Year');

ylabel('Shortfall relative to no damage (%)');

title('Capital Shortfall');


xticks(benchmark_years);

xlim([2035 2265]);

ylim([0 1.10.*max(capital_95)]);


legend( ...
    [h_capital_mean h_capital_95], ...
    'Mean with hurricanes', ...
    '95th-percentile shortfall', ...
    'Location','northwest');

grid on;
box on;


%%Consumption shortfall

nexttile;
hold on;


for kk = 1:numel(benchmark_years)

    plot( ...
        [benchmark_years(kk) benchmark_years(kk)], ...
        [consumption_mean(kk) consumption_95(kk)], ...
        '-', ...
        'Color',joining_colour, ...
        'LineWidth',1.5, ...
        'HandleVisibility','off');

end


h_consumption_mean = plot( ...
    benchmark_years, ...
    consumption_mean, ...
    'o', ...
    'LineStyle','none', ...
    'MarkerSize',9, ...
    'MarkerFaceColor',blue_colour, ...
    'MarkerEdgeColor',blue_colour, ...
    'LineWidth',1.5);


h_consumption_95 = plot( ...
    benchmark_years, ...
    consumption_95, ...
    'd', ...
    'LineStyle','none', ...
    'MarkerSize',9, ...
    'MarkerFaceColor',orange_colour, ...
    'MarkerEdgeColor',orange_colour, ...
    'LineWidth',1.5);


xlabel('Year');

ylabel('Shortfall relative to no damage (%)');

title('Consumption Shortfall');


xticks(benchmark_years);

xlim([2035 2265]);

ylim([0 1.10.*max(consumption_95)]);


legend( ...
    [h_consumption_mean h_consumption_95], ...
    'Mean with hurricanes', ...
    '95th-percentile shortfall', ...
    'Location','northwest');

grid on;
box on;


sgtitle('Hurricane Effects at Selected Years');


export_plot_overwrite( ...
    fig_appendix_e2, ...
    plots_dir, ...
    'Appendix_E2_selected_year_tail_shortfalls.png');


fprintf('\nCompleted successfully.\n');

fprintf('Annual hurricane table saved to:\n%s\n', ...
    regional_hurricane_results_file);

fprintf('Annual Monte Carlo arrays saved to:\n%s\n', ...
    hurricane_monte_carlo_file);

diary off;


%% LOCAL FUNCTION

% Helper for saving figures without leaving older versions behind.

function export_plot_overwrite(fig,plots_dir,filename)

    output_file = ...
        fullfile(plots_dir,filename);


    if isfile(output_file)

        delete(output_file);

    end


    exportgraphics( ...
        fig, ...
        output_file, ...
        'Resolution',300);


    assert(isfile(output_file), ...
        'Plot export failed: %s',output_file);

end