
%% ========================================================================
% STEP F: ANNUAL BELLMAN SAVINGS UNDER HURRICANE RISK
% ========================================================================
%
% Builds on the DICE-2016R-conditioned annual RCAm economy and the
% stochastic hurricane histories generated in Chapter 3. A Bellman problem
% selects the annual regional savings rate based on beginning-of-year
% capital.
%
% Two feedback policies are compared: one that responds to capital without
% anticipating future hurricanes and one that incorporates the expected
% annual hurricane-loss distribution. Both policies are evaluated using
% the same separate out-of-sample hurricane histories.
%
% The five-year savings pathway from Chapter 2 is retained only as a
% reconstruction benchmark. The principal comparison is the
% hurricane-risk-aware policy relative to the policy without hurricane
% anticipation. Monte Carlo evaluation reports the 5th-percentile cutoff
% and the average within the worst 5% of outcomes.
% ========================================================================

%
% STEP F ROADMAP
% --------------
% 1. Load the deterministic annual RCAm economy from Chapter 2.
% 2. Load the annual hurricane histories from Chapter 3.
% 3. Split hurricane histories into training and evaluation samples.
% 4. Compress the training losses into Bellman probability nodes.
% 5. Build capital and savings grids and terminal continuation values.
% 6. Solve two annual feedback savings policies by backward induction.
% 7. Evaluate all policies on identical out-of-sample hurricane histories.
% 8. Validate the reconstruction, calculate mean/tail outcomes and welfare.
% 9. Export tables, figures and the final Step F workspace.
%
clearvars;
clc;
close all;

%% USER CONFIGURATION & DIRECTORY SETUP
%
% This section sets the numerical resolution of the Bellman problem,
% the reporting horizon, the hurricane-distribution approximation,
% and the folders used for figures and saved results.
%
% NK and NS control the number of capital states and savings choices.
% A finer grid gives a more detailed policy function but increases
% computation time.

% Final year shown in the dissertation figures and summary comparisons.
report_end_year = 2250;

% Resolution of the Bellman state and control grids.
NK = 240;
NS = 451;

savings_min = 0.05;
savings_max = 0.50;

% Approximation settings for the annual hurricane-loss distribution.
max_hurricanes_bellman = 4;
max_positive_loss_nodes = 30;

% Capital-grid bounds are defined relative to observed/modelled capital.
capital_grid_min_multiplier = 0.20;
capital_grid_max_multiplier = 1.50;

% Convergence settings for the terminal continuation-value iteration.
continuation_tolerance = 1e-9;
continuation_max_iterations = 5000;

% Fixed seed makes the train/evaluation split reproducible.
random_seed = 6685;

% Lower-tail share used throughout the analysis (5%).
tail_probability = 0.05;

assert(NK >= 50 && NS >= 51, ...
    'The Bellman grids are too small.');

assert(savings_min >= 0 && savings_max < 1 && ...
    savings_min < savings_max, ...
    'The savings bounds are invalid.');

assert(tail_probability > 0 && tail_probability < 0.5, ...
    'The tail probability must lie between zero and one half.');

% Use the location of this script as the project root.
[main_dir,~,~] = fileparts(mfilename('fullpath'));

if isempty(main_dir)
    main_dir = pwd;
end

plots_dir = fullfile(main_dir,'plots');

if ~exist(plots_dir,'dir')
    mkdir(plots_dir);
end

output_dir = fullfile(main_dir,'output','2026-07_RCAM_SAVINGS');

if ~exist(output_dir,'dir')
    mkdir(output_dir);
end

diary_file = fullfile(output_dir,'Step_F_messages.txt');

if isfile(diary_file)
    delete(diary_file);
end

diary(diary_file);

%% LOAD THE ANNUAL REGIONAL RESULTS FROM CHAPTER 2
%
% Step F does not rebuild the regional economy from scratch. It loads
% the deterministic annual RCAm results produced in Chapter 2 (Step C).
% These provide the economic pathway, temperature damages, welfare
% parameters and the five-year savings benchmark used throughout Step F.
%

step_c_file = fullfile(main_dir,'output','2026-07_RCAM', ...
    'STEP_C_annual_results.mat');

assert(isfile(step_c_file), ...
    ['Could not find the annual regional results: %s\n' ...
    'Run the Chapter 2 annual RCAm script first.'], ...
    step_c_file);

step_c = load(step_c_file);

% Explicitly check that every Chapter 2 variable needed by Step F exists.
required_step_c_variables = { ...
    'Params','model_start_year','model_end_year', ...
    'year_dice','H_dice','year_annual','H_annual', ...
    'tfp_annual','pop_annual','omega_annual', ...
    'initial_capital_reg','labour_share_reg','capital_share_reg', ...
    'depreciation_reg','elasmu_reg','prstp_reg', ...
    'savings_opt_five_year','savings_opt_annual', ...
    'terminal_start','terminal_constant_periods', ...
    'K_reg_opt_annual','Ynet_reg_opt_annual','C_reg_opt_annual', ...
    'K_reg_opt_nodamage_annual'};

for vv = 1:numel(required_step_c_variables)
    variable_name = required_step_c_variables{vv};

    assert(isfield(step_c,variable_name), ...
        'Chapter 2 annual results are missing "%s".',variable_name);
end

Params = step_c.Params;

if ~isfield(Params,'consumption_floor')
    Params.consumption_floor = 1e-8;
end

model_start_year = step_c.model_start_year;
model_end_year = step_c.model_end_year;

year_dice = step_c.year_dice(:);
H_dice = step_c.H_dice;

year_annual = step_c.year_annual(:);
H_annual = step_c.H_annual;

tfp_annual = step_c.tfp_annual(:);
pop_annual = step_c.pop_annual(:);
omega_annual = step_c.omega_annual(:);

initial_capital_reg = step_c.initial_capital_reg;
labour_share_reg = step_c.labour_share_reg;
capital_share_reg = step_c.capital_share_reg;
depreciation_reg = step_c.depreciation_reg;
elasmu_reg = step_c.elasmu_reg;
prstp_reg = step_c.prstp_reg;

savings_reference_five_year = step_c.savings_opt_five_year(:);
savings_reference_annual = step_c.savings_opt_annual(:);

terminal_start = step_c.terminal_start;
terminal_constant_periods = step_c.terminal_constant_periods;
terminal_savings = savings_reference_five_year(terminal_start);

K_step_c_annual = step_c.K_reg_opt_annual(:);
Ynet_step_c_annual = step_c.Ynet_reg_opt_annual(:);
C_step_c_annual = step_c.C_reg_opt_annual(:);

K_reference_max = max(step_c.K_reg_opt_nodamage_annual(:));

assert(numel(year_dice) == H_dice && ...
    numel(year_annual) == H_annual, ...
    'The Chapter 2 time indices are inconsistent.');

assert(all(diff(year_dice) == 5), ...
    'The global DICE pathway must remain on its five-year grid.');

assert(all(diff(year_annual) == 1), ...
    'The regional Step F economy must be annual.');

assert(numel(savings_reference_annual) == H_annual, ...
    'The annual Chapter 2 savings pathway has the wrong length.');

terminal_start_year = year_dice(terminal_start);

terminal_start_annual = find( ...
    year_annual >= terminal_start_year,1,'first');

assert(~isempty(terminal_start_annual), ...
    'The Chapter 2 terminal year is outside the annual horizon.');

%% LOAD THE ANNUAL HURRICANE HISTORIES FROM CHAPTER 3
%
% The stochastic hurricane histories generated in Chapter 3 (Step E)
% are loaded here. Each column is one complete annual hurricane history
% and each row corresponds to one model year.
%

step_e_file = fullfile(main_dir,'output', ...
    '2026-07_RCAM_HURRICANE', ...
    'RCAm_hurricane_MonteCarlo_annual.mat');

assert(isfile(step_e_file), ...
    ['Could not find the annual hurricane results: %s\n' ...
    'Run the Chapter 3 annual hurricane script first.'], ...
    step_e_file);

step_e = load(step_e_file, ...
    'year_annual','H_annual','NSIMS', ...
    'HurricaneAnnualLossShare_stoch', ...
    'NumHurricanesAnnual_stoch');

% Check that the saved hurricane file contains the required histories.
required_step_e_variables = { ...
    'year_annual','H_annual','NSIMS', ...
    'HurricaneAnnualLossShare_stoch', ...
    'NumHurricanesAnnual_stoch'};

for vv = 1:numel(required_step_e_variables)
    variable_name = required_step_e_variables{vv};

    assert(isfield(step_e,variable_name), ...
        'Chapter 3 annual results are missing "%s".',variable_name);
end

assert(step_e.H_annual == H_annual && ...
    isequal(step_e.year_annual(:),year_annual), ...
    'Chapters 2 and 3 do not use the same annual horizon.');

hurricane_loss_all = ...
    double(step_e.HurricaneAnnualLossShare_stoch);

hurricane_count_all = ...
    double(step_e.NumHurricanesAnnual_stoch);

assert(isequal(size(hurricane_loss_all), ...
    size(hurricane_count_all)), ...
    'The Chapter 3 hurricane loss and count arrays have different sizes.');

assert(size(hurricane_loss_all,1) == H_annual, ...
    'The Chapter 3 hurricane histories do not match the annual horizon.');

assert(all(hurricane_loss_all >= 0,'all') && ...
    all(hurricane_loss_all < 1,'all'), ...
    'Annual hurricane loss shares must lie in [0,1).');

% Number of complete hurricane histories available for splitting.
available_simulations = size(hurricane_loss_all,2);

%% TRAINING AND EVALUATION HISTORIES
%
% The hurricane histories are split into two non-overlapping samples.
%
%   Training sample:   used to approximate the annual hurricane-loss
%                      distribution inside the Bellman problem.
%   Evaluation sample: used only after the policies have been solved.
%

N_TRAIN = 5000;
N_EVAL = 10000;

assert(available_simulations >= N_TRAIN + N_EVAL, ...
    'Step F requires at least 15,000 independent histories.');

rng(random_seed);

% Randomise history order before assigning training and evaluation sets.
sample_order = randperm(available_simulations);

training_indices = sample_order(1:N_TRAIN);

evaluation_indices = sample_order( ...
    N_TRAIN+1:N_TRAIN+N_EVAL);

assert(isempty(intersect( ...
    training_indices,evaluation_indices)), ...
    'Training and evaluation histories must be disjoint.');

hurricane_loss_train = ...
    hurricane_loss_all(:,training_indices);

hurricane_count_train = ...
    hurricane_count_all(:,training_indices);

hurricane_loss_eval = ...
    hurricane_loss_all(:,evaluation_indices);

%% BUILD THE ANNUAL BELLMAN LOSS DISTRIBUTIONS
%
% The Bellman solver cannot efficiently evaluate thousands of realised
% losses at every capital-savings combination. The training histories
% are therefore compressed into a small set of representative annual
% loss nodes and probability weights.
%
% Years with more than max_hurricanes_bellman storms are excluded from
% the approximation. The code checks that the omitted probability is
% negligible and that the compressed distribution preserves the mean.

loss_nodes = cell(H_annual,1);
loss_weights = cell(H_annual,1);

omitted_probability = zeros(H_annual,1);
distribution_mean_error = zeros(H_annual,1);

for tt = 1:H_annual

    [loss_nodes{tt},loss_weights{tt}, ...
        omitted_probability(tt), ...
        distribution_mean_error(tt)] = ...
        compress_loss_distribution( ...
        hurricane_loss_train(tt,:), ...
        hurricane_count_train(tt,:), ...
        max_hurricanes_bellman, ...
        max_positive_loss_nodes);
end

assert(max(omitted_probability) < 1e-3, ...
    'The probability excluded by the four-storm truncation is too large.');

assert(max(abs(distribution_mean_error)) < 1e-10, ...
    'The compressed annual loss nodes do not preserve the retained mean.');

fprintf('\n=== STEP F BELLMAN DESIGN ===\n');

fprintf('Fixed global DICE nodes:       %d\n',H_dice);
fprintf('Annual regional periods:       %d\n',H_annual);
fprintf('Capital grid points:           %d\n',NK);
fprintf('Savings choices:               %d\n',NS);

fprintf('Positive hurricane nodes:      %d maximum\n', ...
    max_positive_loss_nodes);

fprintf('Hurricane-count truncation:    %d storms\n', ...
    max_hurricanes_bellman);

fprintf('Training histories:            %d\n',N_TRAIN);
fprintf('Evaluation histories:          %d\n',N_EVAL);

fprintf('Maximum omitted probability:   %.3e\n', ...
    max(omitted_probability));

%% COMMON ANNUAL ECONOMIC DATA AND GRIDS
%
% Collect the annual RCAm parameters needed by the Bellman functions
% into one structure (ModelData), then construct:
%
%   capital_grid : possible beginning-of-year capital states;
%   savings_grid : possible annual savings choices.
%
% A logarithmic capital grid provides more resolution at lower capital
% levels while still covering the upper part of the simulated range.

ModelData.H = H_annual;
ModelData.tfp = tfp_annual;
ModelData.population = pop_annual;

ModelData.labour_share = labour_share_reg;
ModelData.capital_share = capital_share_reg;
ModelData.depreciation_factor = 1-depreciation_reg;

ModelData.omega = omega_annual;
ModelData.initial_capital = initial_capital_reg;

% Convert the annual pure rate of time preference into a discount factor.
ModelData.beta = 1./(1+prstp_reg);
ModelData.elasmu = elasmu_reg;
ModelData.consumption_floor = Params.consumption_floor;

ModelData.initial_savings = savings_reference_annual(1);
ModelData.terminal_start = terminal_start_annual;
ModelData.terminal_savings = terminal_savings;

capital_grid_min = ...
    capital_grid_min_multiplier.*initial_capital_reg;

capital_grid_max = ...
    capital_grid_max_multiplier.*K_reference_max;

% Log spacing concentrates more grid points where capital is relatively low.
capital_grid = exp(linspace( ...
    log(capital_grid_min), ...
    log(capital_grid_max),NK))';

savings_grid = ...
    linspace(savings_min,savings_max,NS)';

assert(initial_capital_reg > capital_grid(1) && ...
    initial_capital_reg < capital_grid(end), ...
    'Initial capital is not inside the Bellman capital grid.');

assert(ModelData.initial_savings >= savings_min && ...
    ModelData.initial_savings <= savings_max && ...
    terminal_savings >= savings_min && ...
    terminal_savings <= savings_max, ...
    'The Chapter 2 savings restrictions are outside the Bellman grid.');

% The no-anticipation Bellman problem assumes zero future hurricane loss.
no_risk_nodes = repmat({0},H_annual,1);
no_risk_weights = repmat({1},H_annual,1);

%% TERMINAL CONTINUATION VALUES
%
% The explicit model ends in 2300, but stopping welfare abruptly at the
% final year would distort savings near the horizon. A continuation
% value is therefore calculated under the imposed terminal savings rate.
%
% Two continuation values are computed:
%   1. without hurricane risk;
%   2. with the terminal hurricane-loss distribution.

[continuation_no_risk, ...
    continuation_iterations_no_risk] = ...
    fixed_savings_continuation( ...
    ModelData,capital_grid,terminal_savings, ...
    0,1,continuation_tolerance, ...
    continuation_max_iterations);

[continuation_hurricane_risk, ...
    continuation_iterations_hurricane] = ...
    fixed_savings_continuation( ...
    ModelData,capital_grid,terminal_savings, ...
    loss_nodes{end},loss_weights{end}, ...
    continuation_tolerance, ...
    continuation_max_iterations);

fprintf('Continuation iterations, without anticipation: %d\n', ...
    continuation_iterations_no_risk);

fprintf('Continuation iterations, hurricane-risk aware: %d\n', ...
    continuation_iterations_hurricane);

%% BELLMAN BACKWARD INDUCTION
%
% Solve the annual dynamic-programming problem backwards from the final
% model year to the first year.
%
% The first policy ignores future hurricane risk but can still respond
% to the capital stock inherited from earlier realised shocks.
% The second policy incorporates the expected annual hurricane-loss
% distribution when choosing savings.
%
% The resulting policy matrices map each (year, capital) state to an
% annual savings rate.

fprintf('\nSolving policy without hurricane anticipation...\n');

tic;

[value_no_risk,policy_no_risk, ...
    bellman_bounds_no_risk] = ...
    solve_bellman_policy( ...
    ModelData,capital_grid,savings_grid, ...
    no_risk_nodes,no_risk_weights, ...
    continuation_no_risk);

bellman_minutes_no_risk = toc./60;

fprintf('Solving hurricane-risk-aware policy...\n');

tic;

[value_hurricane_risk,policy_hurricane_risk, ...
    bellman_bounds_hurricane] = ...
    solve_bellman_policy( ...
    ModelData,capital_grid,savings_grid, ...
    loss_nodes,loss_weights, ...
    continuation_hurricane_risk);

bellman_minutes_hurricane = toc./60;

assert(all(isfinite(value_no_risk),'all') && ...
    all(isfinite(value_hurricane_risk),'all'), ...
    'A Bellman value function contains missing or infinite values.');

assert(all(policy_no_risk >= savings_min-1e-12,'all') && ...
    all(policy_no_risk <= savings_max+1e-12,'all') && ...
    all(policy_hurricane_risk >= savings_min-1e-12,'all') && ...
    all(policy_hurricane_risk <= savings_max+1e-12,'all'), ...
    'A Bellman savings policy lies outside the control bounds.');

fprintf('\n=== BELLMAN SOLUTION TIMES ===\n');

fprintf('Without hurricane anticipation: %.3f minutes\n', ...
    bellman_minutes_no_risk);

fprintf('Hurricane-risk aware:        %.3f minutes\n', ...
    bellman_minutes_hurricane);

fprintf('Without-anticipation grid clamps: %d\n', ...
    bellman_bounds_no_risk);

fprintf('Hurricane-risk-aware grid clamps: %d\n', ...
    bellman_bounds_hurricane);

%% FORWARD EVALUATION ON IDENTICAL HURRICANE HISTORIES
%
% After the two Bellman policies are solved, they are simulated forward
% on the SAME 10,000 out-of-sample hurricane histories. This makes the
% comparison paired: differences are caused by the savings rule rather
% than by different hurricane draws.
%
% Three cases are evaluated:
%   Reference              = fixed Chapter 2 savings pathway;
%   No anticipation        = feedback policy without hurricane risk;
%   Hurricane-risk-aware   = feedback policy with hurricane risk.

[K_reference,Ygross_reference, ...
    Ytemperature_reference,Ynet_reference, ...
    Investment_reference,Consumption_reference, ...
    Savings_reference_realised,Welfare_reference, ...
    reference_grid_clamps] = ...
    simulate_policy( ...
    ModelData,capital_grid,[], ...
    savings_reference_annual, ...
    hurricane_loss_eval);

[K_no_risk,Ygross_no_risk, ...
    Ytemperature_no_risk,Ynet_no_risk, ...
    Investment_no_risk,Consumption_no_risk, ...
    Savings_no_risk_realised,Welfare_no_risk, ...
    no_risk_grid_clamps] = ...
    simulate_policy( ...
    ModelData,capital_grid,policy_no_risk,[], ...
    hurricane_loss_eval);

[K_hurricane_risk,Ygross_hurricane_risk, ...
    Ytemperature_hurricane_risk,Ynet_hurricane_risk, ...
    Investment_hurricane_risk,Consumption_hurricane_risk, ...
    Savings_hurricane_risk_realised,Welfare_hurricane_risk, ...
    hurricane_grid_clamps] = ...
    simulate_policy( ...
    ModelData,capital_grid,policy_hurricane_risk,[], ...
    hurricane_loss_eval);

% All evaluation cases face the same continuation of the calibrated
% hurricane process after the reported model horizon.

Welfare_reference = add_terminal_continuation( ...
    Welfare_reference, ...
    K_reference(end,:), ...
    Investment_reference(end,:), ...
    ModelData,capital_grid, ...
    continuation_hurricane_risk);

Welfare_no_risk = add_terminal_continuation( ...
    Welfare_no_risk, ...
    K_no_risk(end,:), ...
    Investment_no_risk(end,:), ...
    ModelData,capital_grid, ...
    continuation_hurricane_risk);

Welfare_hurricane_risk = add_terminal_continuation( ...
    Welfare_hurricane_risk, ...
    K_hurricane_risk(end,:), ...
    Investment_hurricane_risk(end,:), ...
    ModelData,capital_grid, ...
    continuation_hurricane_risk);

% Grid-clamp shares indicate how often simulated capital leaves the
% pre-specified Bellman grid. A very small share supports grid adequacy.
evaluation_states = H_annual.*N_EVAL;

no_risk_clamp_share = ...
    no_risk_grid_clamps./evaluation_states;

hurricane_clamp_share = ...
    hurricane_grid_clamps./evaluation_states;

assert(no_risk_clamp_share < 1e-3 && ...
    hurricane_clamp_share < 1e-3, ...
    ['A forward policy frequently reached the capital-grid boundary. ' ...
    'Expand the capital grid before interpreting the results.']);

%% ZERO-HURRICANE RECONSTRUCTION CHECK
%
% Validation check: remove hurricane losses and run the fixed reference
% savings pathway through the Step F simulator. The resulting capital,
% output and consumption paths should reproduce the deterministic
% Chapter 2 economy to numerical precision.

zero_loss = zeros(H_annual,1);

[K_reconstructed,~,~,Ynet_reconstructed,~, ...
    C_reconstructed,~,~,~] = ...
    simulate_policy( ...
    ModelData,capital_grid,[], ...
    savings_reference_annual,zero_loss);

reconstruction_error = max([ ...
    max(abs(K_reconstructed-K_step_c_annual)); ...
    max(abs(Ynet_reconstructed-Ynet_step_c_annual)); ...
    max(abs(C_reconstructed-C_step_c_annual))]);

assert(reconstruction_error < 1e-9, ...
    'The fixed reference case does not reconstruct the Chapter 2 economy.');

%% POLICY-SPECIFIC NO-DAMAGE COUNTERFACTUALS
%
% Construct a no-temperature-damage counterfactual for each savings
% policy. These counterfactuals provide the policy-specific denominator
% used when expressing total output losses as a percentage gap.
%
% This avoids comparing policies against a no-damage path generated
% under a different savings rule.

NoDamageData = ModelData;
NoDamageData.omega = zeros(H_annual,1);

[~,Ygross_nodamage_reference,~,~,~,~,~,~,~] = ...
    simulate_policy( ...
    NoDamageData,capital_grid,[], ...
    savings_reference_annual,zero_loss);

[~,Ygross_nodamage_no_risk,~,~,~,~,~,~,~] = ...
    simulate_policy( ...
    NoDamageData,capital_grid,policy_no_risk,[],zero_loss);

[~,Ygross_nodamage_hurricane,~,~,~,~,~,~,~] = ...
    simulate_policy( ...
    NoDamageData,capital_grid, ...
    policy_hurricane_risk,[],zero_loss);

OutputGapPct_reference = 100.*( ...
    Ygross_nodamage_reference-Ynet_reference)./ ...
    Ygross_nodamage_reference;

OutputGapPct_no_risk = 100.*( ...
    Ygross_nodamage_no_risk-Ynet_no_risk)./ ...
    Ygross_nodamage_no_risk;

OutputGapPct_hurricane_risk = 100.*( ...
    Ygross_nodamage_hurricane-Ynet_hurricane_risk)./ ...
    Ygross_nodamage_hurricane;

%% SUMMARY STATISTICS
%
% Summarise mean outcomes and lower-tail outcomes across the evaluation
% histories.
%
% For output, capital, consumption and welfare, the adverse tail is the
% LOWER 5% of outcomes. For output-gap percentages, the adverse tail is
% the UPPER 5% because larger losses are worse.
%
% Two tail measures are reported:
%   cutoff       = boundary of the worst 5%;
%   tail average = mean outcome within the worst 5%.

mean_savings_reference = ...
    mean(Savings_reference_realised,2);

mean_savings_no_risk = ...
    mean(Savings_no_risk_realised,2);

mean_savings_hurricane_risk = ...
    mean(Savings_hurricane_risk_realised,2);

mean_output_reference = mean(Ynet_reference,2);
mean_output_no_risk = mean(Ynet_no_risk,2);

mean_output_hurricane_risk = ...
    mean(Ynet_hurricane_risk,2);

% Convert the 5% tail share into an integer number of evaluation histories.
number_tail_evaluation = ceil(tail_probability.*N_EVAL);

% For output, capital, consumption and welfare, adverse outcomes are the
% lowest observations. The cutoff is the last observation included in the
% ranked worst 5%; the tail average uses only those observations.

[output_cutoff_reference,output_tail_average_reference] = ...
    lower_tail_statistics( ...
    Ynet_reference,number_tail_evaluation);

[output_cutoff_no_risk,output_tail_average_no_risk] = ...
    lower_tail_statistics( ...
    Ynet_no_risk,number_tail_evaluation);

[output_cutoff_hurricane_risk, ...
    output_tail_average_hurricane_risk] = ...
    lower_tail_statistics( ...
    Ynet_hurricane_risk,number_tail_evaluation);

[capital_cutoff_reference,capital_tail_average_reference] = ...
    lower_tail_statistics( ...
    K_reference,number_tail_evaluation);

[capital_cutoff_no_risk,capital_tail_average_no_risk] = ...
    lower_tail_statistics( ...
    K_no_risk,number_tail_evaluation);

[capital_cutoff_hurricane_risk, ...
    capital_tail_average_hurricane_risk] = ...
    lower_tail_statistics( ...
    K_hurricane_risk,number_tail_evaluation);

[consumption_cutoff_reference, ...
    consumption_tail_average_reference] = ...
    lower_tail_statistics( ...
    Consumption_reference,number_tail_evaluation);

[consumption_cutoff_no_risk, ...
    consumption_tail_average_no_risk] = ...
    lower_tail_statistics( ...
    Consumption_no_risk,number_tail_evaluation);

[consumption_cutoff_hurricane_risk, ...
    consumption_tail_average_hurricane_risk] = ...
    lower_tail_statistics( ...
    Consumption_hurricane_risk,number_tail_evaluation);

% For output gaps, adverse outcomes are the highest observations.

[output_gap_cutoff_reference, ...
    output_gap_tail_average_reference] = ...
    upper_tail_statistics( ...
    OutputGapPct_reference,number_tail_evaluation);

[output_gap_cutoff_no_risk, ...
    output_gap_tail_average_no_risk] = ...
    upper_tail_statistics( ...
    OutputGapPct_no_risk,number_tail_evaluation);

[output_gap_cutoff_hurricane_risk, ...
    output_gap_tail_average_hurricane_risk] = ...
    upper_tail_statistics( ...
    OutputGapPct_hurricane_risk,number_tail_evaluation);

mean_welfare_reference = mean(Welfare_reference);
mean_welfare_no_risk = mean(Welfare_no_risk);

mean_welfare_hurricane_risk = ...
    mean(Welfare_hurricane_risk);

[welfare_cutoff_reference,welfare_tail_average_reference] = ...
    lower_tail_statistics( ...
    Welfare_reference,number_tail_evaluation);

[welfare_cutoff_no_risk,welfare_tail_average_no_risk] = ...
    lower_tail_statistics( ...
    Welfare_no_risk,number_tail_evaluation);

[welfare_cutoff_hurricane_risk, ...
    welfare_tail_average_hurricane_risk] = ...
    lower_tail_statistics( ...
    Welfare_hurricane_risk,number_tail_evaluation);

mean_welfare_gain_no_risk = ...
    mean(Welfare_no_risk-Welfare_reference);

mean_welfare_gain_hurricane = ...
    mean(Welfare_hurricane_risk-Welfare_reference);

% This paired comparison is the clean measure of hurricane awareness.
% Both policies face exactly the same evaluation histories.

% Positive values mean the hurricane-risk-aware policy produces higher
% welfare than the policy without hurricane anticipation for that SAME
% hurricane history.
paired_welfare_change = ...
    Welfare_hurricane_risk-Welfare_no_risk;

mean_paired_welfare_change = ...
    mean(paired_welfare_change);

median_paired_welfare_change = ...
    median(paired_welfare_change);

[paired_welfare_cutoff,paired_welfare_tail_average, ...
    paired_welfare_tail_sorted] = ...
    lower_tail_statistics( ...
    paired_welfare_change,number_tail_evaluation);

share_welfare_improved = ...
    mean(paired_welfare_change > 0);

% Policy difference in percentage points, not percent.
savings_difference_risk_vs_no_risk = 100.*( ...
    mean_savings_hurricane_risk-mean_savings_no_risk);

% Percentage differences reveal policy effects hidden by plotting levels.
% Cutoff differences compare the boundary of the worst 5%. Tail-average
% differences compare the average outcomes among the ranked worst 5%.

mean_output_difference_pct = 100.*( ...
    mean_output_hurricane_risk-mean_output_no_risk)./ ...
    mean_output_no_risk;

output_cutoff_difference_pct = 100.*( ...
    output_cutoff_hurricane_risk-output_cutoff_no_risk)./ ...
    output_cutoff_no_risk;

output_tail_average_difference_pct = 100.*( ...
    output_tail_average_hurricane_risk- ...
    output_tail_average_no_risk)./ ...
    output_tail_average_no_risk;

capital_cutoff_difference_pct = 100.*( ...
    capital_cutoff_hurricane_risk-capital_cutoff_no_risk)./ ...
    capital_cutoff_no_risk;

capital_tail_average_difference_pct = 100.*( ...
    capital_tail_average_hurricane_risk- ...
    capital_tail_average_no_risk)./ ...
    capital_tail_average_no_risk;

consumption_cutoff_difference_pct = 100.*( ...
    consumption_cutoff_hurricane_risk- ...
    consumption_cutoff_no_risk)./ ...
    consumption_cutoff_no_risk;

consumption_tail_average_difference_pct = 100.*( ...
    consumption_tail_average_hurricane_risk- ...
    consumption_tail_average_no_risk)./ ...
    consumption_tail_average_no_risk;

assert(all(isfinite(mean_output_difference_pct)) && ...
    all(isfinite(output_cutoff_difference_pct)) && ...
    all(isfinite(output_tail_average_difference_pct)) && ...
    all(isfinite(capital_cutoff_difference_pct)) && ...
    all(isfinite(capital_tail_average_difference_pct)) && ...
    all(isfinite(consumption_cutoff_difference_pct)) && ...
    all(isfinite(consumption_tail_average_difference_pct)), ...
    'A percentage-difference series contains a missing or infinite value.');

report_index = year_annual <= report_end_year;
report_years = year_annual(report_index);

[maximum_savings_difference,max_savings_index] = ...
    max(abs(savings_difference_risk_vs_no_risk(report_index)));

maximum_savings_difference_year = ...
    report_years(max_savings_index);

fprintf('\n=== STEP F EXPECTED-WELFARE RESULTS ===\n');

fprintf('Mean welfare, reference:                 %.12g\n', ...
    mean_welfare_reference);

fprintf('Mean welfare, without anticipation:      %.12g\n', ...
    mean_welfare_no_risk);

fprintf('Mean welfare, hurricane-risk aware:      %.12g\n', ...
    mean_welfare_hurricane_risk);

fprintf('Mean welfare gain, without anticipation: %.12g\n', ...
    mean_welfare_gain_no_risk);

fprintf('Mean welfare gain, hurricane-risk aware: %.12g\n', ...
    mean_welfare_gain_hurricane);

fprintf('Mean paired welfare change:              %.12g\n', ...
    mean_paired_welfare_change);

fprintf('Median paired welfare change:            %.12g\n', ...
    median_paired_welfare_change);

fprintf('Share with positive welfare change:      %.4f\n', ...
    share_welfare_improved);

fprintf('\n=== STEP F WORST-5%% EVALUATION ===\n');

fprintf('Evaluation histories in worst 5%%:       %d\n', ...
    number_tail_evaluation);

fprintf('Paired welfare cutoff:                   %.12g\n', ...
    paired_welfare_cutoff);

fprintf('Average paired welfare change, worst 5%%: %.12g\n', ...
    paired_welfare_tail_average);

fprintf('Welfare cutoff, reference:               %.12g\n', ...
    welfare_cutoff_reference);

fprintf('Average welfare within worst 5%%, reference: %.12g\n', ...
    welfare_tail_average_reference);

fprintf('Welfare cutoff, no anticipation:         %.12g\n', ...
    welfare_cutoff_no_risk);

fprintf('Average welfare within worst 5%%, no anticipation: %.12g\n', ...
    welfare_tail_average_no_risk);

fprintf('Welfare cutoff, hurricane-risk aware:    %.12g\n', ...
    welfare_cutoff_hurricane_risk);

fprintf('Average welfare within worst 5%%, hurricane-risk aware: %.12g\n', ...
    welfare_tail_average_hurricane_risk);

fprintf('Maximum mean savings difference:         %.6f pp in %d\n', ...
    maximum_savings_difference, ...
    maximum_savings_difference_year);

fprintf('Without-anticipation forward grid-clamp share: %.3e\n', ...
    no_risk_clamp_share);

fprintf('Hurricane-risk-aware forward grid-clamp share: %.3e\n', ...
    hurricane_clamp_share);

fprintf('Chapter 2 reconstruction error:          %.3e\n', ...
    reconstruction_error);

%% EXPORT ANNUAL RESULTS
%
% Collect the annual policy comparisons and the main diagnostic values
% into CSV files so the numerical results used in the dissertation can
% be inspected without reopening the MATLAB workspace.

% Annual table used for the figures and reported policy comparisons.
annual_results = table( ...
    year_annual, ...
    mean_savings_reference, ...
    mean_savings_no_risk, ...
    mean_savings_hurricane_risk, ...
    savings_difference_risk_vs_no_risk, ...
    mean_output_reference, ...
    mean_output_no_risk, ...
    mean_output_hurricane_risk, ...
    mean_output_difference_pct, ...
    output_cutoff_reference, ...
    output_cutoff_no_risk, ...
    output_cutoff_hurricane_risk, ...
    output_cutoff_difference_pct, ...
    output_tail_average_reference, ...
    output_tail_average_no_risk, ...
    output_tail_average_hurricane_risk, ...
    output_tail_average_difference_pct, ...
    capital_cutoff_reference, ...
    capital_cutoff_no_risk, ...
    capital_cutoff_hurricane_risk, ...
    capital_cutoff_difference_pct, ...
    capital_tail_average_reference, ...
    capital_tail_average_no_risk, ...
    capital_tail_average_hurricane_risk, ...
    capital_tail_average_difference_pct, ...
    consumption_cutoff_reference, ...
    consumption_cutoff_no_risk, ...
    consumption_cutoff_hurricane_risk, ...
    consumption_cutoff_difference_pct, ...
    consumption_tail_average_reference, ...
    consumption_tail_average_no_risk, ...
    consumption_tail_average_hurricane_risk, ...
    consumption_tail_average_difference_pct, ...
    output_gap_cutoff_reference, ...
    output_gap_cutoff_no_risk, ...
    output_gap_cutoff_hurricane_risk, ...
    output_gap_tail_average_reference, ...
    output_gap_tail_average_no_risk, ...
    output_gap_tail_average_hurricane_risk, ...
    'VariableNames',{ ...
    'Year', ...
    'MeanSavingsReference', ...
    'MeanSavingsNoAnticipation', ...
    'MeanSavingsHurricaneRiskAware', ...
    'SavingsDifferenceRiskVsNoRiskPercentagePoints', ...
    'MeanNetOutputReference', ...
    'MeanNetOutputNoAnticipation', ...
    'MeanNetOutputHurricaneRiskAware', ...
    'MeanNetOutputDifferenceRiskVsNoRiskPercent', ...
    'Worst5CutoffNetOutputReference', ...
    'Worst5CutoffNetOutputNoAnticipation', ...
    'Worst5CutoffNetOutputHurricaneRiskAware', ...
    'Worst5CutoffNetOutputDifferencePercent', ...
    'Worst5AverageNetOutputReference', ...
    'Worst5AverageNetOutputNoAnticipation', ...
    'Worst5AverageNetOutputHurricaneRiskAware', ...
    'Worst5AverageNetOutputDifferencePercent', ...
    'Worst5CutoffCapitalReference', ...
    'Worst5CutoffCapitalNoAnticipation', ...
    'Worst5CutoffCapitalHurricaneRiskAware', ...
    'Worst5CutoffCapitalDifferencePercent', ...
    'Worst5AverageCapitalReference', ...
    'Worst5AverageCapitalNoAnticipation', ...
    'Worst5AverageCapitalHurricaneRiskAware', ...
    'Worst5AverageCapitalDifferencePercent', ...
    'Worst5CutoffConsumptionReference', ...
    'Worst5CutoffConsumptionNoAnticipation', ...
    'Worst5CutoffConsumptionHurricaneRiskAware', ...
    'Worst5CutoffConsumptionDifferencePercent', ...
    'Worst5AverageConsumptionReference', ...
    'Worst5AverageConsumptionNoAnticipation', ...
    'Worst5AverageConsumptionHurricaneRiskAware', ...
    'Worst5AverageConsumptionDifferencePercent', ...
    'Worst5CutoffOutputGapReference', ...
    'Worst5CutoffOutputGapNoAnticipation', ...
    'Worst5CutoffOutputGapHurricaneRiskAware', ...
    'Worst5AverageOutputGapReference', ...
    'Worst5AverageOutputGapNoAnticipation', ...
    'Worst5AverageOutputGapHurricaneRiskAware'});

% Compact one-row-per-metric diagnostic summary of the Step F solution.
summary_metric = [ ...
    "Capital grid points"; ...
    "Savings choices"; ...
    "Training histories"; ...
    "Evaluation histories"; ...
    "Tail share"; ...
    "Histories in worst 5 percent"; ...
    "Maximum omitted hurricane probability"; ...
    "Bellman minutes: without hurricane anticipation"; ...
    "Bellman minutes: hurricane-risk aware"; ...
    "Mean welfare: reference"; ...
    "Mean welfare: without hurricane anticipation"; ...
    "Mean welfare: hurricane-risk aware"; ...
    "Mean welfare gain: without hurricane anticipation"; ...
    "Mean welfare gain: hurricane-risk aware"; ...
    "Mean paired welfare change: hurricane-risk aware minus without anticipation"; ...
    "Median paired welfare change: hurricane-risk aware minus without anticipation"; ...
    "Worst-5-percent paired welfare cutoff"; ...
    "Average paired welfare change within worst 5 percent"; ...
    "Share of histories with positive paired welfare change"; ...
    "Worst-5-percent welfare cutoff: reference"; ...
    "Average welfare within worst 5 percent: reference"; ...
    "Worst-5-percent welfare cutoff: no anticipation"; ...
    "Average welfare within worst 5 percent: no anticipation"; ...
    "Worst-5-percent welfare cutoff: hurricane-risk aware"; ...
    "Average welfare within worst 5 percent: hurricane-risk aware"; ...
    "Maximum mean savings difference (pp)"; ...
    "Maximum savings-difference year"; ...
    "Without-anticipation forward grid-clamp share"; ...
    "Hurricane-risk-aware forward grid-clamp share"; ...
    "Chapter 2 reconstruction error"];

summary_value = [ ...
    NK; ...
    NS; ...
    N_TRAIN; ...
    N_EVAL; ...
    tail_probability; ...
    number_tail_evaluation; ...
    max(omitted_probability); ...
    bellman_minutes_no_risk; ...
    bellman_minutes_hurricane; ...
    mean_welfare_reference; ...
    mean_welfare_no_risk; ...
    mean_welfare_hurricane_risk; ...
    mean_welfare_gain_no_risk; ...
    mean_welfare_gain_hurricane; ...
    mean_paired_welfare_change; ...
    median_paired_welfare_change; ...
    paired_welfare_cutoff; ...
    paired_welfare_tail_average; ...
    share_welfare_improved; ...
    welfare_cutoff_reference; ...
    welfare_tail_average_reference; ...
    welfare_cutoff_no_risk; ...
    welfare_tail_average_no_risk; ...
    welfare_cutoff_hurricane_risk; ...
    welfare_tail_average_hurricane_risk; ...
    maximum_savings_difference; ...
    maximum_savings_difference_year; ...
    no_risk_clamp_share; ...
    hurricane_clamp_share; ...
    reconstruction_error];

summary_results = table( ...
    summary_metric,summary_value, ...
    'VariableNames',{'Metric','Value'});

annual_results_file = fullfile( ...
    output_dir,'RCAm_Bellman_annual_results.csv');

summary_results_file = fullfile( ...
    output_dir,'RCAm_Bellman_summary.csv');

writetable(annual_results,annual_results_file);
writetable(summary_results,summary_results_file);

%% FIGURE F1: SAVINGS POLICIES
%
% Plot the average realised annual savings rate under the two feedback
% policies. Only years before the imposed terminal savings rule are
% shown, because later savings values are no longer Bellman choices.
% Terminal years are excluded because their savings rate is imposed by
% the Chapter 2 terminal condition instead of selected by the Bellman problem.

% Use five-year plotting points for readability even though Step F is annual.
figure_years = year_dice( ...
    year_dice <= report_end_year & ...
    year_dice < terminal_start_year);

[~,figure_indices] = ...
    ismember(figure_years,year_annual);

marker_indices = 1:4:numel(figure_years);

col_no_risk = [0.0000 0.4470 0.7410];
col_hurricane = [0.8500 0.3250 0.0980];
col_difference = [0.2000 0.2000 0.2000];

fig_F1 = figure( ...
    'Name','Step F Savings Policies', ...
    'NumberTitle','off', ...
    'Color','w');

plot(figure_years, ...
    100.*mean_savings_no_risk(figure_indices), ...
    '--o', ...
    'LineWidth',2, ...
    'Color',col_no_risk, ...
    'MarkerIndices',marker_indices, ...
    'MarkerSize',4, ...
    'MarkerFaceColor','w');

hold on;

plot(figure_years, ...
    100.*mean_savings_hurricane_risk(figure_indices), ...
    '-o', ...
    'LineWidth',2.5, ...
    'Color',col_hurricane, ...
    'MarkerIndices',marker_indices, ...
    'MarkerSize',4, ...
    'MarkerFaceColor','w');

xlabel('Year');
ylabel('Mean savings rate (%)');
title('Mean Savings Decisions');

legend( ...
    'Policy without hurricane anticipation', ...
    'Hurricane-risk-aware policy', ...
    'Location','best');

grid on;
box on;

export_plot_overwrite( ...
    fig_F1,plots_dir, ...
    'Figure_F1_Savings_policies.png');


%% FIGURE F2: HURRICANE-AWARENESS EFFECT ON SAVINGS
%
% Plot the direct policy effect of hurricane awareness:
% hurricane-risk-aware savings minus savings without anticipation.
% Values are reported in percentage points.

fig_F2 = figure( ...
    'Name','Step F Hurricane Awareness Effect', ...
    'NumberTitle','off', ...
    'Color','w');

plot(figure_years, ...
    savings_difference_risk_vs_no_risk(figure_indices), ...
    '-o', ...
    'LineWidth',2.25, ...
    'Color',col_difference, ...
    'MarkerIndices',marker_indices, ...
    'MarkerSize',4, ...
    'MarkerFaceColor','w');

hold on;

yline(0,'--', ...
    'LineWidth',1.25, ...
    'Color',[0.4 0.4 0.4], ...
    'HandleVisibility','off');

xlabel('Year');
ylabel('Difference in mean savings (percentage points)');
title('Effect of Accounting for Hurricane Risk');

grid on;
box on;

export_plot_overwrite( ...
    fig_F2,plots_dir, ...
    'Figure_F2_Hurricane_awareness_savings_effect.png');
%% FIGURE F3: TAIL OUTPUT DIFFERENCES
%
% Compare the two feedback policies specifically in the lower tail of
% regional net output. The left panel shows the difference in the worst-
% 5% cutoff; the right panel shows the difference in the average outcome
% within the worst 5%.

% Restrict tail comparisons to the reporting horizon and pre-terminal years.
comparison_index = ...
    report_index & year_annual < terminal_start_year;

comparison_years = year_annual(comparison_index);

fig_F3 = figure( ...
    'Name','Step F Bellman Output Differences', ...
    'NumberTitle','off', ...
    'Color','w');

tiledlayout(1,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');

nexttile;

plot(comparison_years, ...
    output_cutoff_difference_pct(comparison_index), ...
    '-', ...
    'LineWidth',2.25, ...
    'Color',col_difference);

hold on;

yline(0,'--', ...
    'LineWidth',1.25, ...
    'Color',[0.4 0.4 0.4], ...
    'HandleVisibility','off');

xlabel('Year');

ylabel( ...
    'Difference relative to policy without anticipation (%)');

title('Worst-5% Cutoff');

grid on;
box on;

nexttile;

plot(comparison_years, ...
    output_tail_average_difference_pct(comparison_index), ...
    '-', ...
    'LineWidth',2.25, ...
    'Color',col_difference);

hold on;

yline(0,'--', ...
    'LineWidth',1.25, ...
    'Color',[0.4 0.4 0.4], ...
    'HandleVisibility','off');

xlabel('Year');

ylabel( ...
    'Difference relative to policy without anticipation (%)');

title('Average within Worst 5%');

grid on;
box on;

sgtitle( ...
    'Effect of Hurricane Awareness on Tail Regional Output');

export_plot_overwrite( ...
    fig_F3,plots_dir, ...
    'Figure_F3_Bellman_output_outcomes.png');

%% FIGURE F4: TAIL CAPITAL AND CONSUMPTION DIFFERENCES
%
% Show how the hurricane-aware savings rule changes lower-tail capital
% and consumption relative to the policy without hurricane anticipation.
% Both the worst-5% cutoff and the average within the worst 5% are shown.

fig_F4 = figure( ...
    'Name','Step F Bellman Lower-Tail Differences', ...
    'NumberTitle','off', ...
    'Color','w');

tiledlayout(1,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');

nexttile;

plot(comparison_years, ...
    capital_cutoff_difference_pct(comparison_index), ...
    '--', ...
    'LineWidth',2, ...
    'Color',col_no_risk);

hold on;

plot(comparison_years, ...
    capital_tail_average_difference_pct(comparison_index), ...
    '-', ...
    'LineWidth',2.25, ...
    'Color',col_hurricane);

yline(0,'--', ...
    'LineWidth',1.25, ...
    'Color',[0.4 0.4 0.4], ...
    'HandleVisibility','off');

xlabel('Year');

ylabel( ...
    'Difference relative to policy without anticipation (%)');

title('Regional Capital');

legend( ...
    'Worst-5% cutoff', ...
    'Average within worst 5%', ...
    'Location','best');

grid on;
box on;

nexttile;

plot(comparison_years, ...
    consumption_cutoff_difference_pct(comparison_index), ...
    '--', ...
    'LineWidth',2, ...
    'Color',col_no_risk);

hold on;

plot(comparison_years, ...
    consumption_tail_average_difference_pct(comparison_index), ...
    '-', ...
    'LineWidth',2.25, ...
    'Color',col_hurricane);

yline(0,'--', ...
    'LineWidth',1.25, ...
    'Color',[0.4 0.4 0.4], ...
    'HandleVisibility','off');

xlabel('Year');

ylabel( ...
    'Difference relative to policy without anticipation (%)');

title('Regional Consumption');

legend( ...
    'Worst-5% cutoff', ...
    'Average within worst 5%', ...
    'Location','best');

grid on;
box on;

sgtitle( ...
    'Effect of Hurricane Awareness on Tail Outcomes');

export_plot_overwrite( ...
    fig_F4,plots_dir, ...
    'Figure_F4_Bellman_lower_tail_outcomes.png');

%% FIGURE F5: WORST 5% OF PAIRED WELFARE CHANGES
%
% Rank the paired welfare changes from worst to best and display only
% the worst 5% of evaluation histories. Because the comparison is paired,
% each welfare difference refers to the same hurricane history under the
% two alternative feedback policies.

% Horizontal axis expresses each ranked tail observation as a share of all
% evaluation histories.
tail_rank_share = 100.*(1:number_tail_evaluation)'./N_EVAL;

fig_F5 = figure( ...
    'Name','Step F Paired Welfare Changes', ...
    'NumberTitle','off', ...
    'Color','w');

plot(tail_rank_share, ...
    paired_welfare_tail_sorted, ...
    '-', ...
    'LineWidth',2.25, ...
    'Color',col_hurricane);

hold on;

yline(0,'--', ...
    'LineWidth',1.25, ...
    'Color',[0.4 0.4 0.4], ...
    'HandleVisibility','off');

xlabel('Cumulative share of evaluation histories (%)');

ylabel([ ...
    'Paired welfare change: hurricane-risk-aware policy minus ' ...
    'policy without anticipation']);

title('Worst 5% of Paired Welfare Changes');

xlim([0,100.*tail_probability]);

grid on;
box on;

welfare_note = sprintf([ ...
    'Tail cutoff: %.4g\n' ...
    'Average within worst 5%%: %.4g\n' ...
    'Worst observation: %.4g'], ...
    paired_welfare_cutoff, ...
    paired_welfare_tail_average, ...
    paired_welfare_tail_sorted(1));

text(0.03,0.97,welfare_note, ...
    'Units','normalized', ...
    'VerticalAlignment','top', ...
    'BackgroundColor','w', ...
    'EdgeColor',[0.7 0.7 0.7]);

export_plot_overwrite( ...
    fig_F5,plots_dir, ...
    'Figure_F5_Bellman_paired_welfare_changes.png');

%% APPENDIX FIGURE: FEEDBACK POLICY FUNCTIONS
%
% This appendix figure shows the actual Bellman policy functions rather
% than only their average realised paths.
%
% For 2050, 2100 and 2150:
%   left  = savings chosen at different capital levels;
%   right = hurricane-aware savings minus no-anticipation savings.
%
% The x-axis is restricted to the central realised capital range so the
% economically relevant part of each policy function is visible.

% Representative early-, middle- and later-horizon years.
policy_years = [2050; 2100; 2150];

[policy_found,policy_indices] = ...
    ismember(policy_years,year_annual);

assert(all(policy_found), ...
    'A policy-function year is outside the horizon.');

assert(all(policy_years < terminal_start_year), ...
    'Policy-function years must precede the terminal savings rule.');

fig_appendix_f1 = figure( ...
    'Name','Step F Policy Functions', ...
    'NumberTitle','off', ...
    'Color','w', ...
    'Position',[100 100 900 1000]);

tl = tiledlayout(3,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');

for pp = 1:numel(policy_years)

    policy_index = policy_indices(pp);

% Use realised capital from both feedback policies to choose a sensible
% x-axis range for this year.
    realised_capital = [ ...
        K_no_risk(policy_index,:), ...
        K_hurricane_risk(policy_index,:)];

    capital_low = ...
        quantile(realised_capital,0.01);

    capital_high = ...
        quantile(realised_capital,0.99);

    capital_padding = max( ...
        0.10.*(capital_high-capital_low), ...
        0.02.*max(capital_high,1));

    capital_limits = [ ...
        max(capital_grid(1), ...
        capital_low-capital_padding), ...
        min(capital_grid(end), ...
        capital_high+capital_padding)];

    if capital_limits(2) <= capital_limits(1)

        capital_limits = ...
            [capital_grid(1),capital_grid(end)];

    end

    %% LEFT PANEL: SAVINGS POLICY

    ax1 = nexttile(2*pp-1);

    plot(capital_grid, ...
        100.*policy_no_risk(policy_index,:), ...
        '--', ...
        'LineWidth',2, ...
        'Color',col_no_risk);

    hold on;

    plot(capital_grid, ...
        100.*policy_hurricane_risk(policy_index,:), ...
        '-', ...
        'LineWidth',2.25, ...
        'Color',col_hurricane);

    xlim(capital_limits);

    xlabel('Capital');
    ylabel('Savings (%)');

    title(sprintf('%d: Savings',policy_years(pp)));

    grid on;
    box on;


    %% RIGHT PANEL: POLICY DIFFERENCE

    ax2 = nexttile(2*pp);

% Difference is hurricane-risk-aware minus no-anticipation, in pp.
    policy_difference = 100.*( ...
        policy_hurricane_risk(policy_index,:) - ...
        policy_no_risk(policy_index,:));

    plot(capital_grid, ...
        policy_difference, ...
        '-', ...
        'LineWidth',2.25, ...
        'Color',col_difference);

    hold on;

    yline(0,'--', ...
        'LineWidth',1.25, ...
        'Color',[0.4 0.4 0.4], ...
        'HandleVisibility','off');

    xlim(capital_limits);

    xlabel('Capital');
    ylabel('Difference (pp)');

    title(sprintf('%d: Difference',policy_years(pp)));

    grid on;
    box on;

end


%% LEGEND

lgd = legend(ax1, ...
    'Without hurricane anticipation', ...
    'Hurricane-risk-aware', ...
    'Orientation','horizontal');

lgd.Layout.Tile = 'south';


%% OVERALL TITLE

sgtitle('Bellman Savings Policies');


%% EXPORT

export_plot_overwrite( ...
    fig_appendix_f1, ...
    plots_dir, ...
    'Appendix_F1_Bellman_policy_functions.png');

%% SAVE STEP F WORKSPACE
%
% Save the solved policies, simulated outcomes, diagnostics and summary
% statistics so that later checks and figures can be reproduced without
% solving the Bellman problem again.

step_f_workspace_file = fullfile( ...
    output_dir,'RCAm_Bellman_annual_results.mat');

save(step_f_workspace_file, ...
    'Params', ...
    'model_start_year','model_end_year', ...
    'year_dice','H_dice', ...
    'year_annual','H_annual', ...
    'NK','NS', ...
    'capital_grid','savings_grid', ...
    'terminal_start_annual','terminal_savings', ...
    'loss_nodes','loss_weights', ...
    'omitted_probability','distribution_mean_error', ...
    'random_seed','training_indices','evaluation_indices', ...
    'tail_probability','number_tail_evaluation', ...
    'value_no_risk','value_hurricane_risk', ...
    'policy_no_risk','policy_hurricane_risk', ...
    'continuation_no_risk','continuation_hurricane_risk', ...
    'savings_reference_annual', ...
    'Savings_reference_realised', ...
    'Savings_no_risk_realised', ...
    'Savings_hurricane_risk_realised', ...
    'K_reference','K_no_risk','K_hurricane_risk', ...
    'Ynet_reference','Ynet_no_risk','Ynet_hurricane_risk', ...
    'Consumption_reference', ...
    'Consumption_no_risk', ...
    'Consumption_hurricane_risk', ...
    'Welfare_reference', ...
    'Welfare_no_risk', ...
    'Welfare_hurricane_risk', ...
    'paired_welfare_change', ...
    'mean_paired_welfare_change', ...
    'median_paired_welfare_change', ...
    'paired_welfare_cutoff', ...
    'paired_welfare_tail_average', ...
    'paired_welfare_tail_sorted', ...
    'share_welfare_improved', ...
    'welfare_cutoff_reference', ...
    'welfare_tail_average_reference', ...
    'welfare_cutoff_no_risk', ...
    'welfare_tail_average_no_risk', ...
    'welfare_cutoff_hurricane_risk', ...
    'welfare_tail_average_hurricane_risk', ...
    'savings_difference_risk_vs_no_risk', ...
    'mean_output_difference_pct', ...
    'output_cutoff_reference', ...
    'output_cutoff_no_risk', ...
    'output_cutoff_hurricane_risk', ...
    'output_cutoff_difference_pct', ...
    'output_tail_average_reference', ...
    'output_tail_average_no_risk', ...
    'output_tail_average_hurricane_risk', ...
    'output_tail_average_difference_pct', ...
    'capital_cutoff_reference', ...
    'capital_cutoff_no_risk', ...
    'capital_cutoff_hurricane_risk', ...
    'capital_cutoff_difference_pct', ...
    'capital_tail_average_reference', ...
    'capital_tail_average_no_risk', ...
    'capital_tail_average_hurricane_risk', ...
    'capital_tail_average_difference_pct', ...
    'consumption_cutoff_reference', ...
    'consumption_cutoff_no_risk', ...
    'consumption_cutoff_hurricane_risk', ...
    'consumption_cutoff_difference_pct', ...
    'consumption_tail_average_reference', ...
    'consumption_tail_average_no_risk', ...
    'consumption_tail_average_hurricane_risk', ...
    'consumption_tail_average_difference_pct', ...
    'output_gap_cutoff_reference', ...
    'output_gap_cutoff_no_risk', ...
    'output_gap_cutoff_hurricane_risk', ...
    'output_gap_tail_average_reference', ...
    'output_gap_tail_average_no_risk', ...
    'output_gap_tail_average_hurricane_risk', ...
    'annual_results','summary_results', ...
    'reconstruction_error', ...
    'bellman_minutes_no_risk', ...
    'bellman_minutes_hurricane', ...
    'no_risk_clamp_share', ...
    'hurricane_clamp_share', ...
    '-v7.3');

fprintf('\nStep F Bellman problem completed successfully.\n');

fprintf('Annual results saved to:\n%s\n', ...
    annual_results_file);

fprintf('Summary results saved to:\n%s\n', ...
    summary_results_file);

fprintf('Workspace saved to:\n%s\n', ...
    step_f_workspace_file);

diary off;

%% ========================================================================
% LOCAL FUNCTIONS
% ========================================================================

% COMPRESS_LOSS_DISTRIBUTION
% Reduce thousands of simulated annual hurricane losses to a small set
% of representative loss nodes and probability weights for the Bellman
% expectation. Zero-loss years are retained explicitly; positive losses
% are sorted into approximately equal-sized bins.
%
function [nodes,weights,omitted_probability,mean_error] = ...
    compress_loss_distribution( ...
    losses,counts,max_count,max_positive_nodes)

    losses = losses(:);
    counts = counts(:);

    retained = counts <= max_count;

    omitted_probability = mean(~retained);

    retained_losses = losses(retained);

    assert(~isempty(retained_losses), ...
        'No hurricane observations remain after count truncation.');

    zero_count = sum(retained_losses == 0);

    positive_losses = ...
        sort(retained_losses(retained_losses > 0));

    retained_count = numel(retained_losses);

    nodes = zeros(0,1);
    weights = zeros(0,1);

    if zero_count > 0
        nodes(end+1,1) = 0;

        weights(end+1,1) = ...
            zero_count./retained_count;
    end

    if ~isempty(positive_losses)

        number_bins = min( ...
            max_positive_nodes,numel(positive_losses));

        edges = round(linspace( ...
            0,numel(positive_losses),number_bins+1));

        for bb = 1:number_bins

            bin_indices = ...
                (edges(bb)+1):edges(bb+1);

            if isempty(bin_indices)
                continue;
            end

            nodes(end+1,1) = ...
                mean(positive_losses(bin_indices)); %#ok<AGROW>

            weights(end+1,1) = ...
                numel(bin_indices)./retained_count; %#ok<AGROW>
        end
    end

    weights = weights./sum(weights);

    retained_mean = mean(retained_losses);
    compressed_mean = sum(nodes.*weights);

    mean_error = compressed_mean-retained_mean;
end

% FIXED_SAVINGS_CONTINUATION
% Approximate welfare beyond the explicit model horizon under a fixed
% terminal savings rate. Iterates on the continuation value until the
% value function converges on the capital grid.
%
function [continuation_value,iterations] = ...
    fixed_savings_continuation( ...
    Data,capital_grid,savings_rate, ...
    loss_nodes,loss_weights,tolerance,max_iter)

    loss_nodes = loss_nodes(:)';
    loss_weights = loss_weights(:);

    continuation_value = ...
        zeros(numel(capital_grid),1);

    terminal_tfp = Data.tfp(end);
    terminal_population = Data.population(end);
    terminal_omega = Data.omega(end);

    for iterations = 1:max_iter

        updated_value = ...
            zeros(size(continuation_value));

        for kk = 1:numel(capital_grid)

            capital = capital_grid(kk);

            gross_output = terminal_tfp.* ...
                (terminal_population./1000).^Data.labour_share.* ...
                capital.^Data.capital_share;

            temperature_output = ...
                gross_output./(1+terminal_omega);

            net_output = ...
                temperature_output.*(1-loss_nodes);

            consumption = ...
                (1-savings_rate).*net_output;

            next_capital = ...
                Data.depreciation_factor.*capital+ ...
                savings_rate.*net_output;

            next_capital = min(max( ...
                next_capital,capital_grid(1)), ...
                capital_grid(end));

            future_value = interp1( ...
                capital_grid,continuation_value, ...
                next_capital,'linear');

            utility = period_utility( ...
                consumption,terminal_population, ...
                Data.elasmu,Data.consumption_floor);

            updated_value(kk) = ...
                (utility+Data.beta.*future_value)* ...
                loss_weights;
        end

        difference = ...
            max(abs(updated_value-continuation_value));

        scale = max(1,max(abs(updated_value)));

        continuation_value = updated_value;

        if difference <= tolerance.*scale
            return;
        end
    end

    error('Terminal continuation value did not converge.');
end

% SOLVE_BELLMAN_POLICY
% Solve the finite-horizon Bellman problem by backward induction.
% For every year and capital state, evaluate all permitted savings choices
% across the relevant hurricane-loss nodes and retain the choice with the
% highest expected current utility plus discounted continuation value.
%
function [value_function,policy_savings,boundary_clamps] = ...
    solve_bellman_policy( ...
    Data,capital_grid,savings_grid, ...
    loss_nodes,loss_weights,continuation_value)

    NK_local = numel(capital_grid);

    value_function = zeros(Data.H,NK_local);
    policy_savings = zeros(Data.H,NK_local);

    boundary_clamps = 0;

    for tt = Data.H:-1:1

        if tt == Data.H
            next_value = continuation_value;
        else
            next_value = value_function(tt+1,:)';
        end

        if tt == 1
            choices = Data.initial_savings;
        elseif tt >= Data.terminal_start
            choices = Data.terminal_savings;
        else
            choices = savings_grid;
        end

        losses = loss_nodes{tt}(:)';
        weights = loss_weights{tt}(:);

        for kk = 1:NK_local

            capital = capital_grid(kk);

            gross_output = Data.tfp(tt).* ...
                (Data.population(tt)./1000).^Data.labour_share.* ...
                capital.^Data.capital_share;

            temperature_output = ...
                gross_output./(1+Data.omega(tt));

            net_output = ...
                temperature_output.*(1-losses);

            consumption = ...
                (1-choices).*net_output;

            next_capital = ...
                Data.depreciation_factor.*capital+ ...
                choices.*net_output;

            boundary_clamps = boundary_clamps+sum( ...
                next_capital(:) < capital_grid(1) | ...
                next_capital(:) > capital_grid(end));

            next_capital = min(max( ...
                next_capital,capital_grid(1)), ...
                capital_grid(end));

            current_utility = period_utility( ...
                consumption,Data.population(tt), ...
                Data.elasmu,Data.consumption_floor);

            future_value = interp1( ...
                capital_grid,next_value, ...
                next_capital,'linear');

            choice_values = ...
                (current_utility+ ...
                Data.beta.*future_value)*weights;

            [value_function(tt,kk),best_choice] = ...
                max(choice_values);

            policy_savings(tt,kk) = ...
                choices(best_choice);
        end
    end
end

% PERIOD_UTILITY
% CRRA utility used by the regional planner. Utility is population-weighted
% and is evaluated using consumption per person. Invalid/non-positive
% consumption receives a very large negative penalty.
%
function utility = period_utility( ...
    consumption,population,elasmu,floor_value)

    invalid = ...
        ~isfinite(consumption) | ...
        consumption <= floor_value;

    consumption = max(consumption,floor_value);

    consumption_per_person = ...
        consumption./population;

    if abs(elasmu-1) < 1e-12

        utility = population.* ...
            log(consumption_per_person);

    else

        utility = population.* ...
            consumption_per_person.^(1-elasmu)./ ...
            (1-elasmu);
    end

    utility(invalid) = -1e30;
end

% ADD_TERMINAL_CONTINUATION
% Add the discounted post-horizon continuation value to the welfare
% generated during the explicit annual simulation.
%
function welfare = add_terminal_continuation( ...
    welfare,last_capital,last_investment, ...
    Data,capital_grid,continuation_value)

    next_capital = ...
        Data.depreciation_factor.*last_capital+ ...
        last_investment;

    next_capital = min(max( ...
        next_capital,capital_grid(1)), ...
        capital_grid(end));

    continuation = interp1( ...
        capital_grid,continuation_value, ...
        next_capital,'linear');

    welfare = welfare+ ...
        Data.beta.^Data.H.*continuation(:);
end

% SIMULATE_POLICY
% Run one savings rule forward across all evaluation histories.
% If feedback_policy is empty, fixed_savings is used. Otherwise the
% year-specific Bellman savings rule is interpolated at realised capital.
%
% Timing within each year:
%   1. observe beginning-of-year capital;
%   2. select savings;
%   3. calculate gross output and chronic temperature impact;
%   4. realise the hurricane output loss;
%   5. allocate net output to consumption and investment;
%   6. carry investment into next year's capital.
%

function [capital,gross_output,temperature_output, ...
    net_output,investment,consumption, ...
    savings_realised,welfare,grid_clamps] = ...
    simulate_policy( ...
    Data,capital_grid,feedback_policy, ...
    fixed_savings,hurricane_loss)

    [H_loss,N_paths] = size(hurricane_loss);

    assert(H_loss == Data.H, ...
        'The hurricane histories do not match the annual horizon.');

    capital = zeros(Data.H,N_paths);
    gross_output = zeros(Data.H,N_paths);
    temperature_output = zeros(Data.H,N_paths);
    net_output = zeros(Data.H,N_paths);
    investment = zeros(Data.H,N_paths);
    consumption = zeros(Data.H,N_paths);
    savings_realised = zeros(Data.H,N_paths);

    capital(1,:) = Data.initial_capital;

    grid_clamps = 0;

    for tt = 1:Data.H

        if isempty(feedback_policy)

            savings_realised(tt,:) = ...
                fixed_savings(tt);

        else

            grid_clamps = grid_clamps+sum( ...
                capital(tt,:) < capital_grid(1) | ...
                capital(tt,:) > capital_grid(end));

            policy_capital = min(max( ...
                capital(tt,:),capital_grid(1)), ...
                capital_grid(end));

            savings_realised(tt,:) = interp1( ...
                capital_grid,feedback_policy(tt,:)', ...
                policy_capital,'linear');
        end

        gross_output(tt,:) = Data.tfp(tt).* ...
            (Data.population(tt)./1000).^Data.labour_share.* ...
            capital(tt,:).^Data.capital_share;

        temperature_output(tt,:) = ...
            gross_output(tt,:)./(1+Data.omega(tt));

        net_output(tt,:) = ...
            temperature_output(tt,:).*( ...
            1-hurricane_loss(tt,:));

        investment(tt,:) = ...
            savings_realised(tt,:).*net_output(tt,:);

        consumption(tt,:) = ...
            net_output(tt,:)-investment(tt,:);

        assert(all( ...
            consumption(tt,:) > Data.consumption_floor), ...
            'A forward simulation produced nonpositive consumption.');

        if tt < Data.H

            capital(tt+1,:) = ...
                Data.depreciation_factor.*capital(tt,:)+ ...
                investment(tt,:);
        end
    end

    period_values = period_utility( ...
        consumption,Data.population, ...
        Data.elasmu,Data.consumption_floor);

    discount_factor = ...
        Data.beta.^((0:Data.H-1)');

    welfare = ...
        sum(discount_factor.*period_values,1)';
end

% LOWER_TAIL_STATISTICS
% Sort outcomes from lowest to highest and return both the cutoff
% defining the worst N observations and their average. Works with
% either one vector of outcomes or a matrix with histories by row.
%
function [cutoff,tail_average,tail_values] = ...
    lower_tail_statistics(values,number_tail)

    assert(number_tail >= 1, ...
        'At least one observation is required in the lower tail.');

    if isvector(values)
        sorted_values = sort(values(:),'ascend');

        assert(number_tail <= numel(sorted_values), ...
            'The requested lower tail exceeds the available observations.');

        tail_values = sorted_values(1:number_tail);
        cutoff = tail_values(end);
        tail_average = mean(tail_values);
    else
        sorted_values = sort(values,2,'ascend');

        assert(number_tail <= size(sorted_values,2), ...
            'The requested lower tail exceeds the available observations.');

        tail_values = sorted_values(:,1:number_tail);
        cutoff = tail_values(:,end);
        tail_average = mean(tail_values,2);
    end
end

% UPPER_TAIL_STATISTICS
% Equivalent tail calculation for variables where HIGH values are
% adverse, such as percentage output losses.
%
function [cutoff,tail_average,tail_values] = ...
    upper_tail_statistics(values,number_tail)

    assert(number_tail >= 1, ...
        'At least one observation is required in the upper tail.');

    if isvector(values)
        sorted_values = sort(values(:),'descend');

        assert(number_tail <= numel(sorted_values), ...
            'The requested upper tail exceeds the available observations.');

        tail_values = sorted_values(1:number_tail);
        cutoff = tail_values(end);
        tail_average = mean(tail_values);
    else
        sorted_values = sort(values,2,'descend');

        assert(number_tail <= size(sorted_values,2), ...
            'The requested upper tail exceeds the available observations.');

        tail_values = sorted_values(:,1:number_tail);
        cutoff = tail_values(:,end);
        tail_average = mean(tail_values,2);
    end
end

% EXPORT_PLOT_OVERWRITE
function export_plot_overwrite( ...
    figure_handle,plots_dir,filename)

    output_file = fullfile(plots_dir,filename);

    if isfile(output_file)
        delete(output_file);
    end

    axes_handles = findall(figure_handle,'Type','axes');

    for aa = 1:numel(axes_handles)
        try
            axes_handles(aa).Toolbar.Visible = 'off';
        catch
            % Older MATLAB versions may not expose an axes toolbar.
        end
    end

    drawnow;

    exportgraphics( ...
        figure_handle,output_file, ...
        'Resolution',300);

    assert(isfile(output_file), ...
        'Plot export failed: %s',output_file);
end
